#!/usr/bin/env python3
"""Report OpenMD A-list terms missing from each dictionary chapter.

The reference file must contain one OpenMD headword per line. Blank lines and
lines beginning with ``#`` are ignored. The report is chapter-local: a term
missing from one chapter is reported there even when another chapter already
contains it, with the covering chapter listed.
"""

from __future__ import annotations

import argparse
import re
import unicodedata
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parent
CHAPTER_DIR = ROOT / "chapters"
AUXILIARY = {"abbreviations.tex", "medical_specialties.tex"}


def normalize(term: str) -> str:
    """Normalize spelling/punctuation for conservative headword matching."""
    term = unicodedata.normalize("NFKD", term).encode("ascii", "ignore").decode()
    term = term.lower()
    term = re.sub(r"\([^)]*\)", " ", term)
    term = re.sub(r"[^a-z0-9]+", " ", term)
    return re.sub(r"\s+", " ", term).strip()


def read_reference(path: Path) -> dict[str, str]:
    terms: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        term = raw.strip()
        if not term or term.startswith("#"):
            continue
        terms.setdefault(normalize(term), term)
    return terms


def chapter_terms(path: Path) -> dict[str, str]:
    terms: dict[str, str] = {}
    text = path.read_text(encoding="utf-8")
    for match in re.finditer(r"\\medterm\{([^{}]+)\}", text):
        term = match.group(1).strip()
        terms.setdefault(normalize(term), term)
    return terms


def chapter_title(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    match = re.search(r"\\chapter\{([^}]+)\}", text)
    return match.group(1) if match else path.stem.replace("_", " ").title()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("reference", type=Path, help="one OpenMD headword per line")
    parser.add_argument(
        "-o", "--output", type=Path, default=ROOT / "openmd_a_missing_by_chapter.md"
    )
    args = parser.parse_args()

    reference = read_reference(args.reference)
    paths = sorted(CHAPTER_DIR.glob("*.tex"))
    chapter_maps = {path: chapter_terms(path) for path in paths}
    owners: dict[str, list[str]] = defaultdict(list)
    for path, terms in chapter_maps.items():
        for key in terms:
            owners[key].append(path.stem)

    clinical = [p for p in paths if p.name not in AUXILIARY]
    auxiliary = [p for p in paths if p.name in AUXILIARY]
    total_missing = 0
    lines = [
        "# OpenMD A-Term Coverage by Chapter",
        "",
        "Generated by `openmd_a_missing_by_chapter.py`.",
        "Matching is case-insensitive and ignores punctuation and parenthetical abbreviations.",
        "The comparison is chapter-local; terms covered elsewhere are labelled accordingly.",
        "",
    ]

    def add_section(path: Path) -> None:
        nonlocal total_missing
        local = chapter_maps[path]
        missing = sorted((key, display) for key, display in reference.items() if key not in local)
        total_missing += len(missing)
        lines.extend([f"## {chapter_title(path)} (`{path.name}`)", ""])
        lines.append(f"Missing OpenMD A-terms: **{len(missing)}**")
        lines.append("")
        if not missing:
            lines.append("None.")
            lines.append("")
            return
        lines.extend(["| Term | Dictionary coverage |", "|---|---|"])
        for key, display in missing:
            other = [name for name in owners.get(key, []) if name != path.stem]
            coverage = ", ".join(other) if other else "Not found elsewhere"
            lines.append(f"| {display} | {coverage} |")
        lines.append("")

    for path in clinical:
        add_section(path)
    lines.extend(["## Auxiliary chapters", ""])
    for path in auxiliary:
        add_section(path)
    lines.extend(
        [
            "## Summary",
            "",
            f"- Reference terms: **{len(reference)}**",
            f"- Clinical chapters: **{len(clinical)}**",
            f"- Auxiliary chapters: **{len(auxiliary)}**",
            f"- Chapter-local missing-term findings: **{total_missing}**",
            "",
        ]
    )
    args.output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
