#!/usr/bin/env ruby

def normalize(value)
  value.downcase.gsub(/[^a-z0-9]/, '')
end

DEFINITIONS = {
  "Kidney Pain vs. Back Pain" => "Kidney pain is usually felt in the flank beneath the ribs and may accompany urinary symptoms, fever, nausea, or blood in the urine. Back pain more often changes with movement or position; severe pain, fever, weakness, or urinary change needs assessment.",
  "Knee and Ankle Pain After Hip Replacement" => "Knee or ankle pain after hip replacement may reflect altered gait and muscle loading, nerve irritation, swelling, a stress injury, infection, or a blood clot. New severe pain, calf swelling, fever, wound drainage, or breathlessness requires prompt evaluation.",
  "Knee Bursitis" => "Knee bursitis is inflammation of a fluid-filled sac around the knee, causing localized swelling, tenderness, and pain with kneeling or movement. Repetitive pressure, trauma, arthritis, gout, or infection can contribute; fever or redness requires urgent review.",
  "Knee Injury and Meniscus Tears" => "A meniscus tear is damage to the cartilage cushion between the thighbone and shinbone, often after twisting or with degeneration. Pain, swelling, catching, or locking may occur; treatment ranges from rehabilitation to surgery according to tear, symptoms, and stability.",
  "Knee Pain Facts" => "Knee pain can arise from ligament or meniscus injury, arthritis, bursitis, tendon disease, gout, infection, nerve disease, or referred hip or spine pain. Deformity, inability to bear weight, fever, a locked joint, or sudden swelling needs assessment.",
  "Kyphosis vs Lordosis Differences and Similarities" => "Kyphosis is excessive backward curvature of the upper spine, while lordosis is excessive inward curvature, usually in the lower spine. Both may be postural or structural and can result from growth disorders, fractures, degeneration, or muscle imbalance.",
  "Larynx Cancer" => "Laryngeal cancer is a malignant tumor of the voice box and may cause persistent hoarseness, swallowing pain, neck mass, ear pain, cough, or breathing difficulty. Diagnosis requires examination and biopsy; treatment depends on site and stage.",
  "Laxatives For Constipation" => "Laxatives treat constipation through fiber and water retention, stool softening, osmotic effects, or increased bowel contractions. Choice depends on cause, duration, age, medicines, kidney function, and obstruction risk; persistent bleeding, vomiting, or severe pain needs evaluation.",
  "Legionnaire Disease and Pontiac Fever" => "Legionnaires disease is a severe pneumonia caused by Legionella, while Pontiac fever is a milder flu-like illness from the same bacteria. Exposure to contaminated water systems is typical; pneumonia, confusion, low oxygen, or high fever requires urgent treatment.",
  "lice vs fleas" => "Lice live on a human host, with head or body lice attaching eggs to hair or clothing, while fleas usually bite humans temporarily after living on animals or in the environment. Identification and environmental or contact treatment differ.",
  "Lipoma vs. Liposarcoma" => "A lipoma is a common benign fatty lump that is soft, mobile, and usually slow-growing. Liposarcoma is a malignant fat-containing tumor and may be deep, enlarging, firm, or painful; a changing or sizable mass requires imaging and specialist assessment.",
  "Loeys-Dietz Syndrome" => "Loeys-Dietz syndrome is an inherited connective-tissue disorder associated with arterial aneurysm or dissection, distinctive skeletal and craniofacial features, allergic disease, and variable organ involvement. Lifelong vascular imaging and coordinated specialist care are important.",
  "Loss of Sense of Smell and Taste With COVID-19" => "COVID-19 can temporarily impair smell and taste through infection or inflammation of nasal and olfactory pathways. Most people improve, but persistent loss, distortion, poor nutrition, or neurologic symptoms warrants follow-up and smell-retraining advice.",
  "Lumbar Lordosis Lower Spine" => "Lumbar lordosis is the normal inward curve of the lower spine; excessive or reduced curvature may be associated with posture, muscle imbalance, hip disease, vertebral deformity, or pain. Examination and imaging are guided by symptoms rather than appearance alone.",
  "Lungs Design And Purpose" => "The lungs exchange oxygen and carbon dioxide through branching airways and microscopic alveoli surrounded by capillaries. The airways filter, warm, and humidify air, while respiratory muscles drive ventilation; disease can impair airflow, diffusion, or blood flow.",
  "Malaria Facts" => "Malaria is a mosquito-borne infection caused by Plasmodium parasites and can produce fever, chills, anemia, confusion, kidney injury, or death. Travel history and testing are crucial because prompt species-specific antimalarial treatment is lifesaving.",
  "malt soup extract" => "Malt extract is a concentrated food ingredient made from germinated grain and contains sugars and other grain components. Its nutritional value and suitability depend on portion, ingredients, gluten content, diabetes management, and the reason it is being used.",
  "Mania vs Hypomania" => "Mania is a sustained elevated, expansive, or irritable mood with increased energy and marked impairment, possible psychosis, or need for hospitalization. Hypomania is milder, lasts at least several days, and causes observable change without severe functional impairment or psychosis.",
  "Marburg Virus History, Symptoms, and Treatment" => "Marburg virus disease is a severe filovirus infection spread through contact with infected body fluids and contaminated materials. Fever, weakness, gastrointestinal symptoms, rash, bleeding, and shock may occur; isolation, supportive critical care, and public-health response are essential.",
  "Melanosis Coli" => "Melanosis coli is dark pigmentation of the colon lining caused by lipofuscin accumulation, classically associated with prolonged stimulant-laxative use. It is usually benign and may fade after stopping the trigger, but the underlying constipation and medication use should be reviewed.",
  "Menstrual Cramps and PMS Medication Guide" => "Menstrual cramps arise from uterine prostaglandins, while premenstrual syndrome causes cyclical physical and emotional symptoms before menstruation. Nonsteroidal anti-inflammatory drugs, hormonal methods, lifestyle measures, or other treatments are selected according to symptoms and contraindications.",
  "Mental Illness" => "Mental illness includes diagnosable disorders affecting mood, thought, behavior, perception, or functioning, such as depression, anxiety, psychosis, and substance-use disorders. Causes are multifactorial, and effective care may combine psychotherapy, medicines, social support, and safety planning.",
  "Mental Illness in Children" => "Mental illness in children may appear as persistent changes in mood, behavior, learning, sleep, appetite, relationships, or development. Evaluation considers age, medical causes, trauma, school context, family history, safety, and the child's strengths and supports.",
  "Migraine and Seizures Symptoms and Signs" => "Migraine can cause recurrent headache with nausea, light sensitivity, or aura, while seizures result from abnormal electrical brain activity and may cause altered awareness, movements, sensations, or post-event confusion. Overlap exists, so history and neurologic evaluation are important.",
  "Migraine and Stroke Symptoms" => "Migraine aura usually develops gradually and resolves, whereas stroke symptoms often begin suddenly and cause persistent focal deficits such as weakness, speech trouble, facial droop, or vision loss. New or atypical neurologic symptoms require emergency stroke assessment.",
  "Migraine vs Headache Whats the Difference" => "A headache is a symptom with many causes; migraine is a neurologic disorder with recurrent attacks often involving throbbing pain, nausea, light or sound sensitivity, and sometimes aura. Diagnosis depends on pattern, associated symptoms, and examination.",
  "Miscarriage Causes and Symptoms" => "Miscarriage is loss of a pregnancy before viability and may cause vaginal bleeding, cramping, passage of tissue, or no symptoms. Causes often involve chromosomal abnormalities, but evaluation considers ectopic pregnancy, infection, uterine factors, and recurrent-loss conditions.",
  "Misophonia" => "Misophonia is an intense emotional or physiologic reaction to specific repetitive sounds, such as chewing or tapping. It is not simple annoyance; behavioral strategies, sound management, and therapy can reduce impairment, while assessment considers anxiety, obsessive-compulsive symptoms, and sensory sensitivity.",
  "Moderate to Severe Disabilities" => "Moderate to severe disability describes substantial limitations in physical, cognitive, sensory, communication, or adaptive functioning that require ongoing support. Needs vary widely and may include medical care, rehabilitation, assistive technology, education, and assistance with daily activities.",
  "Mold Exposure" => "Mold exposure can irritate the eyes, skin, and airways and may worsen asthma or allergic rhinitis; invasive infection is uncommon and mainly affects severely immunocompromised people. Reducing moisture and remediating contaminated areas are more useful than unproven detoxification.",
  "Moles" => "Moles are common collections of pigment-producing melanocytes and are usually benign. A lesion that changes in size, shape, color, symmetry, or symptoms, or differs markedly from others, should be examined for melanoma.",
  "Molluscum Contagiosum Facts" => "Molluscum contagiosum is a contagious poxvirus infection causing small, firm, centrally indented skin bumps. It often resolves spontaneously, but treatment may be considered for discomfort, spread, eczema, genital lesions, or immune suppression.",
  "Morgellons Disease" => "Morgellons is a controversial condition involving distressing skin sensations and the belief that fibers or materials emerge from the skin. Symptoms are real to the person and require respectful evaluation for dermatologic, neurologic, psychiatric, toxic, or infectious causes without reinforcing an unproven explanation.",
  "Motor Fluctuations Causes in Parkinson’s Disease" => "Motor fluctuations in Parkinson disease are changes between good mobility and wearing-off or medication-related involuntary movements as dopamine treatment duration and disease progression change. Adjusting timing, formulations, adjunct medicines, infusion, or surgery may help.",
  "MPS I Mucopolysaccharidosis Type I Hurler Syndrome" => "Mucopolysaccharidosis type I is an inherited lysosomal storage disease caused by alpha-L-iduronidase deficiency. Hurler syndrome is the severe form, with developmental regression, skeletal and airway disease, organ enlargement, corneal clouding, and cardiac involvement; early specialist treatment matters.",
  "MRSA Infection" => "Methicillin-resistant Staphylococcus aureus is a strain of staphylococcus resistant to several beta-lactam antibiotics. It can colonize without illness or cause skin, wound, lung, bone, joint, or bloodstream infection; culture-guided treatment and hygiene reduce spread.",
  "Multidrug-Resistant Extensively Drug-Resistant TB" => "Multidrug-resistant tuberculosis is resistant to key first-line drugs, while extensively drug-resistant TB has additional resistance that greatly limits options. Diagnosis requires molecular or culture testing, and treatment uses prolonged individualized combinations with public-health oversight.",
  "Multiple Myeloma: Deadly to Chronic" => "Multiple myeloma is a plasma-cell cancer that produces a monoclonal protein and can cause bone lesions, anemia, kidney injury, high calcium, infections, and fatigue. It is often treatable as a chronic illness, though relapse and complications remain possible.",
  "Multiple Sclerosis MS and Pregnancy" => "Multiple sclerosis usually does not prevent pregnancy, but symptoms, disease-modifying medicines, relapse risk, delivery planning, and postpartum care require coordination. Some treatments must be stopped or changed, and relapse risk can shift after delivery.",
  "Multiple Sclerosis MS Early Signs and Types" => "Multiple sclerosis is an immune-mediated disease of the central nervous system with episodes or progression of visual, sensory, motor, balance, bladder, cognitive, or fatigue symptoms. Relapsing, progressive, and other patterns guide testing and treatment.",
  "Muscle Spasms" => "Muscle spasms are sudden involuntary contractions caused by exertion, dehydration, electrolyte disturbance, nerve disease, medicines, pregnancy, or musculoskeletal problems. Recurrent, widespread, painful, or weakness-associated spasms need evaluation for an underlying cause.",
  "Muscular Dystrophy: Symptoms, Causes and Types" => "Muscular dystrophies are inherited disorders causing progressive muscle fiber weakness and degeneration. Different types vary in age of onset, inheritance, heart and breathing involvement, contractures, and progression; genetic diagnosis, rehabilitation, and cardiac and respiratory monitoring are important.",
  "Myelodysplastic or Myeloproliferative Neoplasms" => "Myelodysplastic and myeloproliferative neoplasms are clonal bone-marrow disorders causing abnormal blood-cell production. They may produce anemia, infection, bleeding, high counts, enlarged spleen, thrombosis, or progression to acute leukemia; classification and mutation testing guide care.",
  "neck pain and dizziness" => "Neck pain with dizziness may reflect muscle strain, migraine, inner-ear disease, medication, blood-pressure change, or less commonly vascular or neurologic disease. Sudden severe symptoms, weakness, speech or vision change, fainting, or inability to walk require emergency care.",
  "Noise Induced Hearing Loss and Its Prevention" => "Noise-induced hearing loss is permanent injury to inner-ear hair cells from repeated or intense sound exposure, often with tinnitus or difficulty understanding speech. Limiting exposure, increasing distance, taking quiet breaks, and using well-fitted hearing protection reduce risk.",
  "Non-Hodgkins Lymphomas" => "Non-Hodgkin lymphomas are a diverse group of cancers of B, T, or other lymphocytes, ranging from slow-growing to aggressive. Painless lymph-node enlargement, fever, night sweats, weight loss, or extranodal symptoms may occur; biopsy and staging determine treatment.",
  "Nonsteroidal Anti-inflammatory Drugs and Ulcers" => "Nonsteroidal anti-inflammatory drugs can reduce stomach-protective prostaglandins and cause gastritis, ulcers, and gastrointestinal bleeding. Risk rises with age, prior ulcer, anticoagulants, steroids, kidney disease, and high doses; safer alternatives or acid protection may be needed.",
  "Objects Or Insects In Ear" => "An object or insect in the ear canal can cause pain, hearing loss, bleeding, discharge, or a sensation of movement. Do not insert tools or liquids; removal by a clinician is safest when the object is deep, sharp, chemical, or near the eardrum.",
  "Oral Health Problems in Children" => "Children can develop tooth decay, gum inflammation, mouth trauma, ulcers, malocclusion, infections, and developmental dental problems. Fluoride, brushing with supervision, dental visits, injury prevention, and prompt care for pain, swelling, fever, or trauma protect oral health.",
  "Osteogenesis Imperfecta Brittle Bone Disease" => "Osteogenesis imperfecta is an inherited collagen disorder causing fragile bones, recurrent fractures, short stature, dentin abnormalities, hearing loss, and variable skeletal deformity. Care may include fracture prevention, rehabilitation, medicines, surgery, and monitoring of hearing and breathing.",
  "Pain Management: Neuropathic Pain" => "Neuropathic pain arises from injury or dysfunction of nerves and may feel burning, electric, shooting, numb, or hypersensitive. Treatment can include the cause-specific therapy, physical and psychological rehabilitation, topical agents, anticonvulsants, antidepressants, or specialist procedures.",
  "Palpitations Overview" => "Palpitations are awareness of a racing, pounding, fluttering, or skipped heartbeat. They may result from normal stress, stimulants, anemia, thyroid disease, medicines, or arrhythmia; fainting, chest pain, breathlessness, or sustained rapid rhythm requires urgent assessment.",
  "Periodic Paralysis Syndrome" => "Periodic paralysis syndromes are rare inherited or acquired disorders causing episodic muscle weakness associated with abnormal potassium handling or thyroid disease. Attacks may follow rest after exercise, meals, or stress; ECG, potassium testing, and genetic or endocrine evaluation guide care.",
  "Phlebitis and Thrombophlebitis" => "Phlebitis is inflammation of a vein, while thrombophlebitis includes a clot within the inflamed vein. Superficial disease causes localized pain and redness; deep-vein thrombosis can embolize to the lungs and is suspected with limb swelling, pain, or breathlessness.",
  "Pinched Nerve Overview" => "A pinched nerve is compression or irritation of a nerve root or peripheral nerve, causing pain, tingling, numbness, weakness, or radiating symptoms. Causes include disc disease, narrowing, injury, or entrapment; progressive weakness or bowel or bladder change is urgent.",
  "Pinworm Infection" => "Pinworm infection is an intestinal infestation by Enterobius vermicularis, causing nighttime anal itching, disturbed sleep, and sometimes abdominal or genital irritation. Treatment of the person and close household contacts, hygiene, and repeat dosing reduce reinfection.",
  "Plague Facts" => "Plague is an infection caused by Yersinia pestis, usually acquired from infected flea exposure or animals. Bubonic disease causes painful lymph nodes, while pneumonic disease can spread through respiratory droplets; prompt antibiotics and public-health action are essential.",
  "Poison Ivy, Oak, and Sumac" => "Poison ivy, oak, and sumac cause allergic contact dermatitis through urushiol oil, producing intensely itchy streaks or patches of redness, blisters, and swelling. Washing exposed skin and clothing promptly helps; breathing difficulty or facial swelling is an emergency.",
  "Polio Facts" => "Polio is infection with poliovirus, which may be asymptomatic or cause meningitis, muscle weakness, paralysis, and respiratory failure. Vaccination is highly effective prevention; suspected disease requires urgent medical and public-health evaluation.",
  "Polycystic Ovary" => "Polycystic ovaries contain many small follicles and may occur as a normal variant or with polycystic ovary syndrome. PCOS additionally involves ovulatory dysfunction, androgen excess, irregular periods, infertility, acne, or metabolic risk and requires clinical—not ultrasound alone—diagnosis.",
  "Popcorn Lung Bronchiolitis Obliterans" => "Bronchiolitis obliterans is irreversible scarring and narrowing of small airways that can follow toxic inhalation, infection, transplantation, or autoimmune disease. It causes persistent cough and breathlessness with obstructive lung testing; exposure avoidance and specialist care are important.",
  "Powassan Virus Disease" => "Powassan virus disease is a rare tick-borne infection that can cause fever, headache, vomiting, confusion, seizures, meningitis, or encephalitis. Treatment is supportive, and prevention relies on avoiding ticks and removing them promptly.",
  "Pregnancy: Bleeding During the First Trimester" => "First-trimester bleeding may occur with implantation, cervical changes, miscarriage, ectopic pregnancy, or other causes. Assessment uses symptoms, examination, serial pregnancy hormone testing, and ultrasound; heavy bleeding, severe pain, faintness, or shoulder pain is urgent.",
  "Pregnancy: Pain Relief Options for Birth" => "Labor pain relief may include breathing and movement, water, massage, nitrous oxide, intravenous medicines, epidural analgesia, or spinal anesthesia. Choice depends on labor stage, maternal and fetal status, contraindications, availability, and informed preference.",
  "Pregnancy: Placenta Previa" => "Placenta previa occurs when the placenta lies over or near the cervical opening and can cause painless bright-red bleeding, especially later in pregnancy. Digital vaginal examination is avoided until location is known; recurrent bleeding requires obstetric planning and sometimes cesarean delivery.",
  "Pregnancy: Preeclampsia and Eclampsia" => "Preeclampsia is new hypertension during pregnancy with proteinuria or organ dysfunction; eclampsia is the occurrence of seizures. Severe headache, visual symptoms, upper-abdominal pain, shortness of breath, or seizure requires emergency obstetric treatment.",
  "Primary Immunodeficiency Disease PIDD" => "Primary immunodeficiency diseases are inherited disorders of immune development or function that cause unusual, severe, recurrent, or persistent infections and sometimes autoimmunity or inflammation. Evaluation may include blood counts, immunoglobulins, functional tests, and genetic testing.",
  "Primary vs. Secondary Progressive MS" => "Primary progressive multiple sclerosis worsens from onset without clear early relapses, while secondary progressive MS follows an earlier relapsing course and later develops steady progression. Disability, MRI activity, relapses, and treatment response guide management.",
  "Prostatitis vs BPH Enlarged Prostate Gland" => "Prostatitis is inflammation or infection of the prostate and may cause pelvic pain, painful urination, fever, or urinary symptoms. Benign prostatic hyperplasia is age-related prostate enlargement causing weak stream, hesitancy, and incomplete emptying without infection.",
  "Psychotic Disorders" => "Psychotic disorders involve impaired reality testing, such as hallucinations, delusions, disorganized thought, or marked behavioral change. Causes include schizophrenia-spectrum illness, mood disorders, substances, medicines, neurologic disease, and medical illness; new psychosis requires prompt assessment and safety planning."
}.freeze

def excluded_title?(term)
  term =~ /^(Can |Do |Does |Are |Is |What |Why |How |Best |Fastest |First |Early |Easiest |Eat |Eating |Exercises |Foods |Figure |Father|Dealing|Difference|Differences|Disadvantages|Dandruff vs|Drink |Drinking |Duration|Good |Get |Get Rid|Having |Healthy Living|Health and|Tips|Ways|Should |Before|After|Common|Cochlear|Four |Exposure|Directives|Advantages|Coping|Dream|Weigh|Weight|Life Expectancy|Life With|Lose |Losing |Long-Term|Low FODMAP|Low-Glycemic|Left Brain|Labor Duration|Labor Pain|Gastroparesis Diet|Loss, Grief|Grief|Glycemic|Gambling|Healthy|Main |Make |Meaning |Most |Mirena |Mens Health|Menopause and Sex|Metabolic Syndrome Diet|MyPlate|Natural |Nature |Neuroendocrine Tumor the Same|Neurological Disorders Cause|Nightshade|Nonsurgical|Normal |Oldest |Overcoming|Ovulation Calculator|Palmitic|Parenting|Parkinson.s Disease: Eating|Part of the Body|Pathological Liar|Physically Fit|Poison Control|Prebiotics|Pregnancy Symptoms|Pregnancy: Your Guide|Protect Your Teeth|PMS vs|Pimple vs|Pancoast Tumor Lung Cancer|Pancreatic Cancer Be|Pancreatic Neuroendocrine Tumors Metastasize|Most Effective|Non-Itchy|Non-Small Cell.*vs|Oxycodone vs|Over-the-Counter|Osteoblast vs|Osteoarthritis vs|Patellofemoral Syndrome|Pneumonia Facts|Pain From|PMS|Pediatric|Pelvic Inflammatory Disease Without|Pelvic Pain|Pimple vs)/i
end

def latex_escape(value)
  value.gsub('&', '\\&').gsub('%', '\\%').gsub('#', '\\#')
end

%w[K L M N O P].each do |letter|
  input = "/tmp/medicinenet_#{letter}_terms.txt"
  output = "chapters/med_terms_#{letter.downcase}.tex"
  text = File.read(output)
  existing = text.scan(/^\\medterm\{([^}]*)\}/).flatten.to_h { |title| [normalize(title), true] }
  terms = File.readlines(input, chomp: true).reject { |term| excluded_title?(term) }
  additions = []

  terms.each do |term|
    next if existing[normalize(term)]
    definition = DEFINITIONS[term]
    unless definition
      opening = term.index('(')
      definition = "Alternate index label for #{latex_escape(term[(opening + 1)...-1])}." if opening
    end
    raise "No specific definition for #{term}" unless definition
    additions << [term, definition]
  end

  File.open(output, 'a') do |file|
    additions.each do |term, definition|
      file.puts
      file.puts "\\medterm{#{term}} #{definition}"
      file.puts
      file.puts '\\textbf{Synonyms}:'
    end
  end
  puts "#{letter}: added #{additions.length} terms"
end
