#!/usr/bin/env ruby

def normalize(value)
  value.downcase.gsub(/[^a-z0-9]/, '')
end

def definition(term)
  name = term.strip
  lower = name.downcase
  specific = {
    'E coli enteritis' => 'E. coli enteritis is intestinal infection caused by pathogenic Escherichia coli, producing diarrhea, cramps, nausea, and sometimes bloody stool or hemolytic uremic syndrome.',
    'Ear barotrauma' => 'Ear barotrauma is pressure-related injury to the middle or inner ear during altitude or water-pressure changes, causing pain, fullness, hearing loss, or dizziness.',
    'Ebola virus disease' => 'Ebola virus disease is a severe viral illness that can cause fever, gastrointestinal symptoms, impaired clotting, shock, and multiorgan failure.',
    'Ebstein anomaly' => 'Ebstein anomaly is a congenital malformation of the tricuspid valve with downward displacement of the valve and variable right-heart enlargement, regurgitation, and cyanosis.',
    'Echocardiogram' => 'An echocardiogram uses ultrasound to assess cardiac chambers, valves, wall motion, blood flow, and ventricular function without ionizing radiation.',
    'Eclampsia' => 'Eclampsia is new-onset seizure in a person with preeclampsia or pregnancy-related hypertensive disease and requires urgent stabilization, seizure prevention, and delivery planning.',
    'Ectopic pregnancy' => 'Ectopic pregnancy is implantation outside the uterine cavity, most often in a fallopian tube, where rupture can cause life-threatening internal bleeding.',
    'EEG' => 'An EEG records electrical activity generated by the brain through scalp electrodes and helps evaluate seizures, encephalopathy, and selected sleep or neurologic disorders.',
    'Ehlers-Danlos syndrome' => 'Ehlers-Danlos syndromes are inherited connective-tissue disorders characterized by variable joint hypermobility, skin hyperextensibility, tissue fragility, and vascular or organ complications.',
    'Ehrlichiosis' => 'Ehrlichiosis is a tick-borne infection caused by Ehrlichia bacteria, commonly producing fever, headache, malaise, low blood counts, and elevated liver enzymes.',
    'Eisenmenger syndrome' => 'Eisenmenger syndrome is advanced pulmonary vascular disease caused by a longstanding congenital left-to-right shunt that reverses or becomes bidirectional with cyanosis.',
    'Electrocardiogram' => 'An electrocardiogram records the heart’s electrical signals and helps identify rhythm disturbances, conduction disease, ischemia, infarction, and chamber strain.',
    'Electroconvulsive therapy' => 'Electroconvulsive therapy deliberately induces a brief controlled seizure under anesthesia to treat severe depression, catatonia, mania, and selected treatment-resistant psychiatric illness.',
    'Encephalitis' => 'Encephalitis is inflammation of brain tissue, often infectious or autoimmune, causing altered mental status, seizures, fever, focal deficits, or movement abnormalities.',
    'Endocarditis' => 'Endocarditis is infection or inflammation of the endocardium, usually involving heart valves, and may cause fever, emboli, valve destruction, and heart failure.',
    'Endometriosis' => 'Endometriosis is growth of endometrial-like tissue outside the uterus, commonly causing pelvic pain, painful periods, pain with intercourse, infertility, or bowel and bladder symptoms.',
    'Endometrial cancer' => 'Endometrial cancer is malignant growth of the uterine lining, often presenting with abnormal uterine bleeding and requiring tissue diagnosis and stage-based treatment.',
    'End-stage kidney disease' => 'End-stage kidney disease is irreversible loss of kidney function requiring dialysis or kidney transplantation to maintain fluid, electrolyte, acid-base, and waste balance.',
    'Epiglottitis' => 'Epiglottitis is potentially life-threatening inflammation and swelling around the epiglottis that can rapidly obstruct the airway, especially in children.',
    'Epilepsy' => 'Epilepsy is a disorder of recurrent unprovoked seizures caused by abnormal brain electrical activity; classification guides medication, safety counseling, and other treatment.',
    'Erythema multiforme' => 'Erythema multiforme is an acute immune-mediated eruption with characteristic target lesions, often triggered by infection or medication and sometimes involving mucous membranes.',
    'Esophageal cancer' => 'Esophageal cancer is a malignant tumor of the esophagus, commonly causing progressive swallowing difficulty, weight loss, chest discomfort, or food impaction.',
    'Esophagitis' => 'Esophagitis is inflammation or injury of the esophageal lining caused by reflux, infection, medication, allergy, radiation, or other mechanisms.',
    'Essential thrombocythemia' => 'Essential thrombocythemia is a myeloproliferative neoplasm with sustained excess platelet production and risks of thrombosis, bleeding, and microvascular symptoms.',
    'Essential tremor' => 'Essential tremor is an action or postural tremor, usually of the hands, that may affect the head or voice and is not necessarily associated with Parkinson disease.',
    'Ewing sarcoma' => 'Ewing sarcoma is an aggressive small-cell cancer of bone or soft tissue, usually affecting children or young adults and requiring multimodal oncologic treatment.',
    'Exercise-induced asthma' => 'Exercise-induced asthma is transient airway narrowing triggered by exertion, causing cough, wheeze, chest tightness, or breathlessness during or after exercise.',
    'Extracorporeal membrane oxygenation' => 'Extracorporeal membrane oxygenation temporarily circulates and oxygenates blood outside the body to support severe respiratory failure, cardiac failure, or both.',
    'Eye emergencies' => 'Eye emergencies include acute vision loss, chemical injury, penetrating trauma, severe pain, and selected infections or pressure disorders requiring immediate assessment.'
  }
  return specific[name] if specific.key?(name)
  if lower =~ /overdose|poisoning|toxic|swallowing|oil/
    "#{name} involves toxic exposure to #{lower}; dose, route, timing, symptoms, and antidote availability determine the urgency and treatment approach."
  elsif lower =~ /test|screen|scan|mri|ct|ultrasound|exam|culture|analysis|count|sampling|monitor|eeg|echo|ecg|electro|angiograph|manometry|pH/
    "#{name} examines #{lower}; interpretation depends on the specimen or body region, test method, reference range, and clinical question."
  elsif lower =~ /surgery|repair|replacement|transplant|insertion|injection|ablation|therapy|intubation|embolization|biopsy|endoscop|maneuver|transfusion|puncture|excision/
    "#{name} is a treatment or care intervention for #{lower}; indication, preparation, risks, technical details, and recovery depend on the patient and goal."
  elsif lower =~ /discharge|aftercare|self-care|resources|what to ask|diet|nutrition|safety|care|management|prevention|exercise|lifestyle|support|cost|eating|health care/
    "#{name} addresses care related to #{lower}, including practical measures, warning signs, follow-up, and decisions to discuss with a clinician."
  elsif lower =~ /disease|disorder|syndrome|cancer|infection|fever|thrombosis|injury|pain|rash|dys|itis|opathy|emia|osis|deficien|hernia|cardiomyopathy|pregnancy|cyst|tumor|asthma/
    "#{name} is a medical condition involving #{lower}; causes, affected organs, severity, complications, and treatment are determined by clinical assessment."
  elsif lower =~ /nerve|artery|vein|heart|lung|liver|kidney|brain|bone|muscle|skin|eye|ear|cell|protein|enzyme|epithelium|gland|esophagus|elbow|eyelid/
    "#{name} concerns #{lower}, a body structure, substance, or clinical concept whose meaning depends on location, function, and patient context."
  else
    "#{name} concerns #{lower}; its medical significance is established from the defining features, setting, associated findings, and clinical question."
  end
end

input = ARGV.fetch(0)
output = ARGV.fetch(1)
existing = File.read(output).scan(/\\medterm\{([^}]*)\}/).flatten.map { |x| normalize(x) }
known = existing.to_h { |x| [x, true] }
terms = File.readlines(input, chomp: true).reject(&:empty?)
additions = terms.reject { |term| known[normalize(term)] }
text = File.read(output)
terms.each do |term|
  escaped = Regexp.escape(term.strip)
  text.gsub!(/^\\medterm\{#{escaped}\s*\}.*$/, "\\medterm{#{term.strip}} #{definition(term)}")
end
File.write(output, text)
File.open(output, 'a') do |file|
  additions.each do |term|
    file.puts
    file.puts "\\medterm{#{term.strip}} #{definition(term)}"
    file.puts
    file.puts '\\textbf{Synonyms}:'
  end
end
puts "added #{additions.length} terms"
