#!/usr/bin/env ruby

def normalize(value)
  value.downcase.gsub(/[^a-z0-9]/, '')
end

DEFINITIONS = {
  "Abscessed Tooth Guide" => "An abscessed tooth contains a localized collection of pus caused by bacterial infection, usually from decay, a crack, or gum disease. Dental drainage, root-canal treatment, or extraction may be needed; fever, facial swelling, or difficulty swallowing requires urgent care.",
  "Aches, Pain, Fever" => "Aches, pain, and fever are common symptoms of infection, inflammation, injury, medication effects, or other illness. The pattern, duration, associated symptoms, and temperature help determine whether evaluation or urgent treatment is needed.",
  "Achondroplasia vs Pseudoachondroplasia Differences" => "Achondroplasia is a common skeletal dysplasia caused by altered FGFR3 signaling, whereas pseudoachondroplasia is usually caused by COMP or related cartilage-matrix variants. Both cause disproportionate short stature, but their spine, joint, radiographic, and inheritance features differ.",
  "Acquired Generalized and Inherited Lipodystrophy" => "Lipodystrophy is abnormal loss or absence of adipose tissue. Acquired generalized forms develop after an immune or other trigger, while inherited forms result from gene variants; both can cause severe insulin resistance, diabetes, high triglycerides, and fatty liver.",
  "Actinic Purpura Vs Senile Purpura" => "Actinic or senile purpura consists of painless purple bruises on sun-damaged, thin skin, especially on the hands and forearms. It reflects fragile dermal vessels and connective tissue rather than a dangerous bleeding disorder, although widespread or unexplained bruising needs assessment.",
  "Acute and Chronic Bursitis" => "Bursitis is inflammation of a fluid-filled bursa that cushions a joint. Acute bursitis may follow trauma, infection, or sudden overuse; chronic bursitis reflects repeated pressure or inflammatory disease and causes localized pain, swelling, and tenderness with movement.",
  "Addison’s Disease How Treated and Can It Be Cured" => "Addison disease is primary adrenal insufficiency, in which the adrenal glands do not produce enough cortisol and often aldosterone. Lifelong hormone replacement usually controls it; stress dosing and emergency injectable steroid plans help prevent adrenal crisis.",
  "Adenoids and Tonsils" => "The adenoids and tonsils are lymphoid tissues in the upper airway that participate in immune surveillance. Enlargement or recurrent infection can cause mouth breathing, snoring, sleep apnea, swallowing problems, or recurrent throat disease and may require medical or surgical evaluation.",
  "Adult ADHD" => "Adult attention-deficit/hyperactivity disorder is a persistent pattern of inattention, impulsivity, and hyperactivity that begins in childhood and impairs work, relationships, or daily organization. Diagnosis uses developmental history and symptom assessment; treatment may combine skills-based therapy and medication.",
  "Adult-Onset Asthma" => "Adult-onset asthma is variable airway inflammation and narrowing that begins in adulthood, producing episodic wheezing, cough, chest tightness, or shortness of breath. Diagnosis uses symptoms and lung-function testing, and treatment reduces triggers and airway inflammation.",
  "Advance Medical Directives" => "Advance medical directives record a person's preferences for future medical care and identify a health-care proxy when the person cannot decide. They may address resuscitation, life support, artificial nutrition, and other treatments, and should be reviewed as circumstances change.",
  "Advantages and Disadvantages of a Hospital Birth" => "A hospital birth provides immediate access to obstetric, anesthesia, newborn, and surgical services, which can be important when complications arise. Tradeoffs may include more routine interventions, less control over setting, and separation or transfer policies that vary by facility.",
  "Advantages and Disadvantages of Hysterectomy" => "Hysterectomy removes the uterus and permanently ends pregnancy and menstruation. It can treat cancer, fibroids, severe bleeding, prolapse, or pain, but involves operative risks, recovery time, and possible effects on ovarian function or pelvic organs depending on the procedure.",
  "After a Positive Ovulation Test Are You Fertile?" => "A positive ovulation test detects a rise in luteinizing hormone that usually precedes ovulation by about one to two days. Fertility is highest around this interval, but timing varies and the test does not confirm that an egg was released.",
  "After Endolymphatic Sac Decompression Surgery" => "After endolymphatic sac decompression, follow-up focuses on wound healing, vertigo, hearing, balance, and recurrence of inner-ear symptoms. Activity and ear-care instructions depend on the operation, and persistent severe vertigo, drainage, fever, or facial weakness needs prompt review.",
  "Alcohol Abuse and Alcoholism" => "Alcohol use disorder is a medical condition involving impaired control over drinking despite harm, craving, tolerance, or withdrawal. Treatment can include medically supervised withdrawal, counseling, peer support, and medications that reduce drinking or relapse risk.",
  "Alcohol and Teens" => "Alcohol exposure during adolescence can impair judgment, increase injury and unsafe-sex risk, and affect developing brain systems involved in learning and impulse control. Early screening, supportive communication, treatment of coexisting mental-health problems, and limiting access reduce harm.",
  "Allergic Cascade" => "The allergic cascade is the sequence in which an allergen activates immune cells, including IgE-bearing mast cells, causing release of histamine and other mediators. This produces symptoms such as itching, swelling, mucus, wheezing, hives, or anaphylaxis.",
  "Allergy" => "An allergy is an inappropriate immune response to a normally harmless substance such as pollen, food, medicine, insect venom, or animal proteins. Symptoms range from localized rhinitis or hives to life-threatening anaphylaxis.",
  "Allergy Treatment Begins At Home" => "Home allergy care may include reducing exposure to the trigger, improving indoor air filtration, washing after outdoor exposure, saline nasal rinsing with safe water, and using recommended medicines correctly. Breathing difficulty, throat swelling, faintness, or widespread symptoms require emergency care.",
  "ALS vs. MS Differences and Similarities" => "Amyotrophic lateral sclerosis primarily destroys motor neurons and causes progressive weakness, while multiple sclerosis causes immune-mediated lesions in the brain and spinal cord with varied sensory, visual, motor, or cognitive symptoms. Examination, imaging, laboratory testing, and time course distinguish them.",
  "Alternative Therapy for Multiple Sclerosis" => "Complementary approaches for multiple sclerosis may support symptoms such as fatigue, pain, stress, or mobility but do not replace disease-modifying treatment. Exercise, rehabilitation, mindfulness, and selected supplements should be discussed with clinicians because interactions and unproven claims are common.",
  "Alternative Treatments for Hot Flashes" => "Nonhormonal approaches to hot flashes include cooling strategies, layered clothing, sleep and stress measures, cognitive behavioral therapy, and selected prescription medicines. Herbal products have variable evidence and can interact with medicines; treatment choice depends on symptoms and medical history.",
  "Alzheimer's Disease Causes, Stages, and Symptoms" => "Alzheimer disease is a progressive neurodegenerative disorder causing decline in memory and other thinking abilities, followed by increasing difficulty with communication, judgment, movement, and self-care. Progression varies, and evaluation looks for reversible contributors and other dementias.",
  "Alzheimer's Disease Symptoms and Stages" => "Alzheimer disease commonly progresses from subtle memory and planning problems to loss of independence, language and recognition difficulties, and eventually extensive assistance needs. Symptoms and speed of progression differ, so staging supports care planning rather than predicting an exact timeline.",
  "Am I Depressed" => "Depression is more than temporary sadness: it involves persistent low mood or loss of interest with changes in sleep, appetite, energy, concentration, movement, self-worth, or hope. Thoughts of self-harm require immediate emergency or crisis support.",
  "Amblyopia Lazy Eye" => "Amblyopia is reduced vision in an eye that did not develop normal visual processing during childhood, often because of unequal focusing power, misalignment, or obstruction. Early treatment may include glasses, patching or blurring the stronger eye, and correction of the underlying problem.",
  "Amebiasis Entamoeba histolytica Infection" => "Amebiasis is infection with Entamoeba histolytica, acquired through fecally contaminated food, water, or hands. It may cause diarrhea or dysentery and can spread to the liver; stool testing and appropriate tissue-active and luminal treatment are used.",
  "Anabolic Steroid Abuse" => "Anabolic-androgenic steroid misuse can cause infertility, testicular shrinkage, acne, mood changes, high blood pressure, adverse cholesterol changes, liver injury, and cardiovascular events. Stopping may produce withdrawal symptoms and is safest with medical support.",
  "Anemia How Is It Treated and Can It Be Cured" => "Anemia is reduced oxygen-carrying capacity from low red-cell number or hemoglobin. Treatment depends on cause, such as iron or vitamin deficiency, blood loss, kidney disease, inflammation, or inherited disease; correcting the cause may resolve it, while some conditions require long-term management.",
  "Aneurysm vs Stroke Which Is Worse" => "An aneurysm is a weakened, bulging blood-vessel wall, whereas a stroke is brain injury from interrupted blood flow or bleeding. A ruptured brain aneurysm can cause a hemorrhagic stroke, and the seriousness of either condition depends on location, size, bleeding, and neurologic injury.",
  "Angina Symptoms" => "Angina is chest discomfort caused by inadequate blood flow to heart muscle, commonly from coronary artery disease. Pressure or squeezing may spread to the arm, jaw, back, or shoulder and can occur with exertion; new, severe, or resting symptoms require emergency assessment.",
  "Ankle Pain and Tendinitis" => "Ankle pain may result from sprain, fracture, arthritis, tendon inflammation, nerve disease, infection, or referred pain. Tendinitis causes pain along an affected tendon and often worsens with loading; swelling, deformity, inability to bear weight, fever, or numbness warrants evaluation.",
  "antidiabetics-oral" => "Oral antidiabetic medicines lower blood glucose through different mechanisms, including increasing insulin release, improving insulin sensitivity, reducing hepatic glucose production, or increasing urinary glucose loss. Selection considers kidney function, hypoglycemia risk, weight, cardiovascular disease, and cost.",
  "Antiemetics" => "Antiemetics are medicines used to prevent or treat nausea and vomiting. Drug classes act on serotonin, dopamine, histamine, acetylcholine, or neurokinin pathways; choice depends on the cause, age, pregnancy, other medicines, heart rhythm risk, and hydration status.",
  "Anxiety Separation (Separation Anxiety)" => "Separation anxiety is excessive fear or distress when separated from an attachment figure, beyond what is expected for developmental stage. It can cause avoidance, physical complaints, sleep difficulty, and school impairment and is treated with behavioral therapy and, when needed, medication.",
  "Apnea Sleep (Sleep Apnea)" => "Sleep apnea consists of repeated pauses or reductions in breathing during sleep. Obstructive apnea results from upper-airway collapse, while central apnea reflects reduced respiratory drive; untreated disease can cause daytime sleepiness, impaired concentration, hypertension, and cardiovascular risk.",
  "Are Antiperspirants Harmful" => "Antiperspirants reduce sweating, usually with aluminum salts, and are generally safe when used on intact skin as directed. Irritation or contact dermatitis can occur; persistent excessive sweating, a new generalized change, or symptoms of illness deserves medical evaluation.",
  "Are Bananas Bad for Kidneys?" => "Bananas are not universally harmful to the kidneys, but they contain potassium. People with advanced kidney disease or medicines that raise potassium may need individualized portions and laboratory monitoring rather than making dietary changes without clinical advice.",
  "Are Bananas Bad if You Are Trying to Lose Weight?" => "Bananas can fit a weight-loss eating pattern because they provide carbohydrate, fiber, and nutrients, but portion size and total energy intake determine weight change. Pairing fruit with a balanced meal or protein may improve satiety.",
  "Are Bananas Fattening for You?" => "Bananas are not inherently fattening; body weight changes when average energy intake exceeds expenditure. They contain natural carbohydrate and calories, so serving size matters, especially in calorie-restricted diets or diabetes meal planning.",
  "Are Bananas Good for Diabetes" => "People with diabetes can often include bananas in portions that fit their carbohydrate plan. Ripeness, serving size, total meal composition, glucose-lowering treatment, and individual glucose response influence their effect on blood sugar.",
  "Are Bean Sprouts Good for You" => "Bean sprouts provide fiber and micronutrients but can harbor Salmonella, E. coli, or other pathogens because they grow in warm, moist conditions. Cooking sprouts thoroughly lowers infection risk, especially for pregnant people, children, older adults, and immunocompromised people.",
  "Are Bedbugs Contagious" => "Bedbugs do not spread from person to person like an infection, but they can travel in clothing, luggage, bedding, and furniture. Bites cause itchy skin reactions in some people; control requires treating the environment rather than treating the person for contagion.",
  "Are Belly Bands Safe During Pregnancy" => "A pregnancy belly band may temporarily support the abdomen or reduce pelvic and back discomfort when properly fitted. It should not be tight enough to impair breathing, circulation, digestion, or fetal movement, and persistent pain or swelling needs obstetric evaluation.",
  "Are Blood Clots Normal in Early Pregnancy" => "Small clots or spotting in early pregnancy are not automatically normal and can occur with benign cervical changes, miscarriage, or ectopic pregnancy. Heavy bleeding, one-sided pain, shoulder pain, dizziness, or fainting requires urgent assessment.",
  "Are Breast Implants Worth It?" => "Whether breast implants are worthwhile depends on goals, expected appearance, health, cost, and willingness to accept revision surgery and implant-related risks. Complications include capsular contracture, rupture, infection, changes in sensation, and rare implant-associated malignancy.",
  "Are C-Sections Really That Bad" => "Cesarean delivery can be lifesaving and appropriate, but it is major abdominal surgery with risks such as infection, bleeding, blood clots, organ injury, and longer recovery. It can also affect risks in later pregnancies; decisions depend on maternal and fetal circumstances.",
  "Are Canker Sores Contagious" => "Canker sores are shallow ulcers inside the mouth and are not contagious. They may be associated with minor trauma, stress, nutritional deficiency, immune disease, or other triggers; unusually large, frequent, persistent, or systemic-associated ulcers need evaluation.",
  "Are Carrots Healthy for Babies?" => "Carrots can provide fiber and beta-carotene for babies when introduced in an age-appropriate, soft form. Choking risk depends on texture and shape, so whole raw pieces are unsafe for young children; introduce foods according to developmental readiness.",
  "Are Collagen Supplements Good for You?" => "Collagen supplements provide amino-acid peptides that may modestly affect skin elasticity or joint symptoms in some studies, but evidence and product quality vary. They do not replace adequate dietary protein, and allergies, contaminants, cost, and medicine interactions should be considered.",
  "Are Contact Lenses Better Than Glasses?" => "Contact lenses provide a wider field of view and may be preferred for sports or appearance, while glasses are easier to maintain and avoid direct corneal infection risk. The better option depends on prescription, eye health, comfort, hygiene, and ability to follow care instructions.",
  "Are Contact Lenses Safe?" => "Contact lenses are generally safe with proper fitting, hand hygiene, cleaning, replacement, and wear time. Sleeping or swimming in lenses and using contaminated solutions raises the risk of microbial keratitis, which can threaten vision and requires urgent care for pain, redness, or light sensitivity.",
  "Are CPAP Machines Worth It" => "Continuous positive airway pressure can reduce obstructive sleep-apnea events, improve oxygenation and daytime alertness, and lower some health risks when used consistently. Benefit depends on correct diagnosis, mask fit, comfort, adherence, and follow-up adjustment.",
  "Are Dental Implants Worth It" => "Dental implants can restore chewing and support a crown, bridge, or denture after tooth loss. Success depends on bone, gums, smoking, diabetes control, oral hygiene, surgical risk, time, and cost; complications include infection, bone loss, nerve injury, and implant failure.",
  "Are Dimples Rare?" => "Facial dimples are common inherited variations caused by differences in the muscles or connective tissue beneath the skin. They are usually harmless and do not indicate a medical disorder.",
  "Are Earwigs Harmful to Humans" => "Earwigs are not known to crawl into human ears as a normal behavior and are generally harmless. They can pinch defensively, but they do not have venom; a bite or pinch should be cleaned and observed for infection.",
  "Are Eggs Bad for Pancreatitis" => "Eggs are not automatically prohibited after pancreatitis, but tolerance depends on disease severity and dietary fat. During recovery, clinicians may recommend a gradual return to lower-fat meals; persistent pain, vomiting, or inability to eat needs medical review.",
  "Are Eggs Good for an Upset Stomach" => "Plain, well-cooked eggs may be tolerated during recovery from some stomach illnesses and provide protein, but they can worsen symptoms for people with particular food intolerance, reflux, gallbladder disease, or infection. Hydration and the underlying cause remain more important than one food.",
  "Are Gastric Bypasses Reversible?" => "Gastric bypass anatomy can sometimes be revised, but reversal is complex and not routine. It may be considered for serious complications or specific nutritional problems and carries operative risks; long-term dietary and supplement needs continue to require monitoring.",
  "Are Ground-Glass Opacities Common" => "Ground-glass opacity is a hazy area on chest CT in which vessels remain partly visible. It is a radiologic finding rather than a diagnosis and can reflect infection, inflammation, edema, hemorrhage, fibrosis, or early malignancy; interpretation depends on pattern and clinical context.",
  "Are Heated Blankets Bad for You" => "Heated blankets are generally safe when used according to instructions, but burns, overheating, fire, and electrical injury can occur. People with reduced sensation, limited mobility, or inability to respond to heat should use extra caution or avoid them.",
  "Are Hiccups Good or Bad" => "Hiccups are involuntary diaphragm contractions that are usually brief and harmless. Persistent or recurrent hiccups can result from irritation, medication, metabolic disease, or nervous-system disorders and may interfere with eating, sleeping, or breathing.",
  "Are Hives and Rash the Same Thing" => "Hives are a specific type of rash consisting of raised, itchy welts that usually move or fade within 24 hours. Other rashes may involve scales, blisters, bruising, or fixed lesions, so appearance and duration help identify the cause.",
  "Are Katydids Dangerous?" => "Katydids are generally harmless insects and do not normally attack people. Contact may cause a minor pinch or local irritation, but severe reactions are unusual; rapidly spreading swelling, breathing trouble, or systemic symptoms need emergency care.",
  "Are Loofahs Bad for You?" => "Loofahs can harbor bacteria and fungi when kept damp and may irritate or abrade skin. Rinse and dry them thoroughly, replace them regularly, and avoid sharing or using them on broken, infected, or freshly shaved skin.",
  "Are Menstrual Cups Bad for You" => "Menstrual cups are generally safe when correctly fitted, cleaned, and emptied on schedule. Possible problems include irritation, pain, leakage, difficult removal, and rare toxic shock syndrome; use during an intrauterine-device placement should be discussed with a clinician.",
  "Are Pregnancy Pillows Good for Back Pain?" => "Pregnancy pillows can support the abdomen, hips, or knees and may improve sleep-related back or pelvic discomfort. They do not treat serious causes of pain; weakness, numbness, fever, bleeding, contractions, or severe persistent pain needs obstetric advice.",
  "Are Rubella and German Measles the Same Thing" => "Rubella and German measles are the same viral infection. It is usually mild in children and adults but can cause miscarriage, fetal death, or congenital rubella syndrome when infection occurs during pregnancy; vaccination prevents it.",
  "Are Shirataki Noodles Bad for You?" => "Shirataki noodles contain glucomannan fiber and are generally safe in appropriate portions with adequate fluid. Large amounts may cause bloating, diarrhea, choking, or obstruction, and they can affect absorption of medicines if taken too close together.",
  "Are Skin Rashes Contagious" => "Some rashes spread through infection, while others result from allergy, irritation, inflammation, medication, or internal disease and are not contagious. Fever, rapid spread, mucosal involvement, severe pain, blistering, or breathing symptoms warrants prompt evaluation.",
  "Are Smelly Farts Healthy? Types of Farts" => "Intestinal gas and odor are normal results of swallowed air and bacterial fermentation of food. A sudden persistent change with weight loss, bleeding, severe pain, vomiting, fever, or altered bowel habits can indicate gastrointestinal disease.",
  "Are Strawberries Good for Your Stomach?" => "Strawberries provide fiber and vitamin C and are tolerated by many people. Their acidity, seeds, or fermentable carbohydrates can aggravate reflux, allergy, or bowel symptoms in some individuals, so response and portion size matter.",
  "Are Warts Caused by Being Dirty" => "Warts are caused by infection with human papillomavirus, not by being dirty. The virus enters small breaks in skin and spreads through contact or shared surfaces; hygiene can reduce spread but does not imply blame.",
  "Are Warts Contagious?" => "Warts can spread through direct contact, shared items, or self-inoculation from one body site to another. Avoid picking them, keep them covered when appropriate, and do not share towels, nail tools, or footwear.",
  "Are Widow’s Peaks Attractive" => "A widow's peak is a V-shaped hairline variant with no established medical significance. Its appearance is a normal trait and does not reliably indicate personality, health, or genetic disease.",
  "Are You Too Sick to Work" => "Whether illness warrants staying home depends on symptoms, contagiousness, ability to function safely, job demands, and workplace policy. Fever, vomiting, significant diarrhea, uncontrolled respiratory symptoms, or a positive contagious-infection test commonly support staying home and seeking advice.",
  "Arsenic Poisoning" => "Arsenic poisoning results from acute or chronic exposure to inorganic or organic arsenic. It can cause gastrointestinal illness, cardiovascular instability, neuropathy, characteristic skin changes, anemia, and increased cancer risk; suspected exposure requires poison-control or emergency guidance.",
  "Asbestos-Related Disorders" => "Asbestos exposure can cause pleural plaques, diffuse pleural thickening, asbestosis, lung cancer, and mesothelioma after a long latency. Risk increases with cumulative exposure and smoking, and evaluation may include occupational history, imaging, and lung-function testing.",
  "Asthma Complexities" => "Asthma varies in trigger, severity, airway inflammation, and response to treatment. Difficult-to-control symptoms may reflect poor inhaler technique, ongoing exposure, incorrect diagnosis, comorbid disease, or severe asthma requiring specialist assessment.",
  "Asthma Medications" => "Asthma medicines include controller treatments that reduce airway inflammation and reliever treatments that quickly relax airway muscle. The regimen is guided by symptom frequency, lung function, exacerbation risk, age, pregnancy, technique, and response.",
  "Asthma Overview" => "Asthma is a chronic disorder of variable airway inflammation and narrowing that causes wheezing, cough, chest tightness, or breathlessness. Symptoms fluctuate with triggers, and management combines an individualized action plan, inhaled medicines, trigger reduction, and monitoring.",
  "Asthma: Over The Counter Treatment" => "Over-the-counter products do not replace prescription asthma evaluation or a rescue plan. Some may temporarily relieve symptoms but can delay treatment of dangerous airway obstruction; worsening breathlessness, difficulty speaking, cyanosis, or poor response to a reliever is an emergency.",
  "Astigmatism Overview" => "Astigmatism is an irregular curvature of the cornea or lens that prevents light from focusing at one retinal point. It can cause blurred or distorted vision, eyestrain, and headaches and is corrected with glasses, contact lenses, or selected procedures.",
  "At What Age Do Late Talkers Talk" => "Late talking varies widely, but a child with delayed words, gestures, understanding, or social communication should be assessed rather than watched indefinitely. Hearing testing and developmental evaluation can identify language disorder, autism, hearing loss, or other causes and support early therapy.",
  "At What Age Does Gender Identity Develop" => "Gender identity is a person's internal sense of gender and develops through a combination of biological, developmental, and social factors. Children may express a gender identity early, and supportive, nonjudgmental care is appropriate regardless of whether identity changes over time.",
  "At What Age Is a Parent Not Legally Responsible" => "Legal responsibility for a child varies by jurisdiction, age, custody arrangement, and circumstances such as disability or emancipation. Medical consent and financial responsibility may follow different rules, so local legal or social-service advice is needed for a specific case.",
  "At What Age is Co-Sleeping Safe with Your Baby" => "The safest sleep arrangement for an infant is a separate, firm, flat sleep surface in the same room as a caregiver, without pillows, loose bedding, or soft objects. Bed-sharing carries increased suffocation and sleep-related death risk, especially for young infants and when adults smoke, drink, or use sedating drugs.",
  "At What Age Should You Stop Birth Control?" => "Birth control is usually continued until pregnancy is no longer possible, which is commonly around menopause but varies by method and health history. Stopping requires a plan for pregnancy prevention or conception and review of bleeding, migraine, clot, cancer, and medication risks.",
  "At What Stage Is CLL Treated?" => "Chronic lymphocytic leukemia is often observed when it is asymptomatic and stable. Treatment is generally started for progressive anemia or thrombocytopenia, enlarging disease, significant symptoms, rapid progression, or complications, using blood counts, examination, genetics, and symptoms to guide timing.",
  "At What Stage of Cancer is Chemotherapy Used" => "Chemotherapy may be used before surgery or radiation, after local treatment, as the main treatment for disseminated disease, or for symptom control. The stage and regimen depend on cancer type, molecular features, treatment goals, organ function, and patient preferences.",
  "Atopic Dermatitis vs Contact Dermatitis" => "Atopic dermatitis is a chronic eczema associated with skin-barrier dysfunction and an atopic tendency, while contact dermatitis follows exposure to an irritant or allergen. Distribution, exposure history, recurrence, and patch testing can help distinguish them; both require skin protection and targeted treatment.",
  "Atopic Dermatitis vs Psoriasis" => "Atopic dermatitis commonly causes intensely itchy, poorly defined eczema in flexural areas, while psoriasis produces well-demarcated thicker plaques with silvery scale and may involve nails or extensor surfaces. Overlap occurs, so examination and history guide diagnosis.",
  "Atrial Fibrillation AFib Treatment Drugs" => "Medicines for atrial fibrillation may slow the ventricular rate, restore or maintain rhythm, or reduce stroke risk with anticoagulation. Choice depends on symptoms, heart structure, kidney function, bleeding risk, other diseases, and whether rhythm control is appropriate.",
  "Atrial Fibrillation vs. Ventricular Fibrillation" => "Atrial fibrillation is a rapid, irregular atrial rhythm that may allow the ventricles to pump, whereas ventricular fibrillation is chaotic ventricular activity that stops effective circulation. Ventricular fibrillation causes cardiac arrest and requires immediate defibrillation and resuscitation.",
  "Atrial Flutter vs. Atrial Fibrillation" => "Atrial flutter usually has a rapid organized atrial circuit with characteristic sawtooth activity, while atrial fibrillation has chaotic atrial activation and an irregular ventricular response. Both can cause palpitations and stroke risk and may require rate control, rhythm treatment, and anticoagulation.",
  "Attention Deficit Hyperactivity Disorder in Teens" => "ADHD in teenagers causes persistent inattention, impulsivity, or hyperactivity that interferes with school, relationships, driving, or organization. Assessment includes childhood history and screening for learning disorders, sleep problems, substance use, anxiety, depression, and other conditions.",
  "Autism and Communication" => "Autism can affect social communication, language development, nonverbal interaction, and the use of communication for shared attention or relationships. Individualized speech-language therapy, visual supports, augmentative communication, and respectful environmental accommodations can improve participation.",
  "Average Life Expectancy After a Liver Transplant?" => "Life expectancy after liver transplantation varies with the original disease, recipient health, graft function, rejection, infection, cancer recurrence, and adherence to follow-up. Lifelong immunosuppression, surveillance, preventive care, and management of cardiovascular and metabolic risks are essential.",
  "Avian Flu (Avian Influenza (Bird Flu))" => "Avian influenza is infection with influenza A viruses adapted primarily to birds. Human infection is uncommon but can be severe after contact with infected birds or mammals; exposure history, respiratory symptoms, and public-health testing guide evaluation and treatment.",
  "Avian Influenza (Bird Flu)" => "Avian influenza is infection with influenza A viruses adapted primarily to birds. Human infection is uncommon but can be severe after contact with infected birds or mammals; exposure history, respiratory symptoms, and public-health testing guide evaluation and treatment."
}.freeze

def latex_escape(value)
  value.gsub('&', '\\&').gsub('%', '\\%').gsub('#', '\\#')
end

input = ARGV.fetch(0)
output = ARGV.fetch(1)
text = File.read(output)
existing_titles = text.scan(/^\\medterm\{([^}]*)\}/).flatten
existing_by_normalized = existing_titles.to_h { |title| [normalize(title), title] }
terms = File.readlines(input, chomp: true).reject do |term|
  term =~ /^(Health A-Z|Drugs & Medications|Diseases & Conditions|Medical Slideshows|Procedures & Tests|Medications|Image Collection|Quizzes|More\.\.\.)$/
end
additions = []

terms.each do |term|
  actual_title = existing_by_normalized[normalize(term)]
  if actual_title
    next
  end
  definition = DEFINITIONS[term]
  unless definition
    opening = term.index('(')
    if opening
      reference = term[(opening + 1)...-1]
      definition = "Alternate index label for #{latex_escape(reference)}."
    end
  end
  raise "No specific definition for #{term}" unless definition
  additions << [term, definition]
end

File.open(output, 'a') do |file|
  additions.each do |term, definition|
    file.puts
    file.puts "\\medterm{#{term}} #{definition}"
    file.puts
    file.puts '\\textbf{Synonyms}:'
  end
end
puts "added #{additions.length} terms"
