#!/usr/bin/env ruby

def normalize(value)
  value.downcase.gsub(/[^a-z0-9]/, '')
end

DEFINITIONS = {
  "E. Coli 0157:H7" => "E. coli O157:H7 is a Shiga-toxin-producing strain that can cause severe diarrhea, abdominal cramps, and bloody stool. It may lead to hemolytic uremic syndrome, especially in children; antibiotics and antidiarrheals require careful medical guidance.",
  "Earliest Signs of Increased Intracranial Pressure" => "Early increased intracranial pressure may cause worsening headache, vomiting, visual changes, drowsiness, slowed thinking, or a change in behavior. It can result from bleeding, tumor, swelling, infection, or hydrocephalus and requires prompt evaluation when progressive.",
  "Ear Infection" => "An ear infection may involve the outer canal, middle ear, or inner ear, with symptoms such as pain, drainage, hearing change, fever, or vertigo. Treatment depends on the site, cause, age, severity, and complications.",
  "Ear Wax" => "Earwax is a protective mixture produced in the ear canal that traps debris and limits microbial growth. It usually clears without help; inserting objects can push it inward or injure the canal and eardrum.",
  "Ectopic Pregnancy" => "An ectopic pregnancy implants outside the uterine cavity, most often in a fallopian tube. It can rupture and cause life-threatening internal bleeding; one-sided pain, vaginal bleeding, shoulder pain, dizziness, or fainting in early pregnancy requires urgent care.",
  "Eczema Facts" => "Eczema is a group of itchy inflammatory skin disorders involving barrier dysfunction, dryness, redness, scaling, or oozing. Triggers and subtypes vary, and care combines moisturization, trigger reduction, topical treatment, and management of infection when present.",
  "Edema" => "Edema is swelling caused by excess fluid in tissues. It may result from venous disease, heart or kidney failure, liver disease, inflammation, medicines, pregnancy, or lymphatic obstruction; sudden one-sided swelling or breathlessness needs urgent evaluation.",
  "Ehlers-Danlos Syndrome" => "Ehlers-Danlos syndromes are inherited connective-tissue disorders that can cause joint hypermobility, skin hyperextensibility, easy bruising, chronic pain, and tissue fragility. Vascular forms can cause serious arterial or organ complications and require specialized care.",
  "Elbow Pain" => "Elbow pain can arise from tendinitis, bursitis, arthritis, fracture, dislocation, nerve compression, infection, or referred neck or shoulder disease. Trauma, deformity, fever, weakness, numbness, or inability to move warrants prompt assessment.",
  "Encephalitis" => "Encephalitis is inflammation of brain tissue caused by infection, autoimmune disease, or less commonly other processes. Fever, headache, confusion, seizures, behavior change, or reduced consciousness requires emergency evaluation and often hospital treatment.",
  "Encephalopathy" => "Encephalopathy is a broad term for altered brain function caused by metabolic, toxic, infectious, structural, vascular, or systemic disease. Confusion, drowsiness, personality change, seizures, or reduced consciousness requires evaluation for a reversible cause.",
  "Encopresis" => "Encopresis is repeated stool soiling in a child beyond the age expected for toilet training, commonly associated with chronic constipation and stool retention. Treatment empties the bowel, maintains soft regular stools, and addresses behavioral or developmental factors without shame.",
  "Endocarditis" => "Endocarditis is infection or inflammation of the heart lining or valves, usually from bacteria or fungi in the bloodstream. Fever, murmur, embolic symptoms, or persistent illness may occur; prolonged targeted antimicrobial treatment and sometimes surgery are required.",
  "Endometriosis" => "Endometriosis is growth of endometrium-like tissue outside the uterus, causing pelvic pain, painful periods or sex, bowel or bladder symptoms, infertility, or no symptoms. Treatment may include analgesia, hormonal suppression, surgery, or fertility care.",
  "End-Stage COPD: Signs, Symptoms, and Prognosis" => "Advanced COPD may cause severe persistent breathlessness, low exercise tolerance, frequent exacerbations, weight loss, oxygen dependence, and respiratory failure. Prognosis varies; pulmonary rehabilitation, inhaled treatment, oxygen when indicated, advance care planning, and palliative support are important.",
  "Enlarged Spleen" => "An enlarged spleen, or splenomegaly, may result from infection, liver or blood disease, cancer, inflammation, or congestion. It can cause fullness or pain and increases vulnerability to rupture; the cause and blood counts guide evaluation.",
  "Enthesitis and Enthesopathy" => "Enthesitis is inflammation where a tendon, ligament, or fascia attaches to bone; enthesopathy includes degenerative and other disorders at that site. It is associated with overuse, arthritis, and spondyloarthritis and causes localized pain and stiffness.",
  "Eosinophilic Esophagitis" => "Eosinophilic esophagitis is chronic immune-mediated inflammation of the esophagus with eosinophil accumulation. It can cause swallowing difficulty, food impaction, reflux-like pain, and feeding problems; treatment uses dietary elimination, swallowed topical steroids, dilation, or biologic therapy.",
  "Eosinophilic Fasciitis" => "Eosinophilic fasciitis is inflammation and thickening of the fascia, causing painful swelling, symmetric skin induration, and restricted joint movement, often after exertion. Blood eosinophilia may occur; diagnosis may require imaging or biopsy and treatment usually involves immunosuppression.",
  "Epilepsy and Seizures: How to Treat" => "Epilepsy is a tendency to recurrent unprovoked seizures caused by abnormal electrical activity in the brain. Treatment may include antiseizure medicine, surgery, dietary therapy, or neuromodulation according to seizure type, cause, risks, and response.",
  "Erythema Nodosum" => "Erythema nodosum is painful inflammation of fat beneath the skin, producing tender red nodules usually on the shins. It may follow infection, medication, pregnancy, inflammatory bowel disease, sarcoidosis, or another inflammatory condition.",
  "Esophageal Cancer" => "Esophageal cancer is a malignant tumor of the esophagus, commonly presenting later with progressive difficulty swallowing, weight loss, chest discomfort, or bleeding. Endoscopy with biopsy establishes diagnosis, and treatment depends on stage and tumor biology.",
  "Esophagitis" => "Esophagitis is inflammation of the esophageal lining caused by reflux, medicines, infection, allergy, radiation, or other injury. It may cause painful or difficult swallowing, chest pain, or bleeding; treatment targets the cause and protects healing tissue.",
  "Essential Mixed Cryoglobulinemia" => "Mixed cryoglobulinemia is an immune-complex disorder in which proteins precipitate in the cold and inflame small vessels. It can cause purpura, joint pain, weakness, kidney disease, neuropathy, or ulcers and is often associated with infection, autoimmune disease, or lymphoma.",
  "Eustachian Tube Problems" => "Eustachian-tube dysfunction prevents normal pressure equalization and middle-ear drainage, causing fullness, popping, muffled hearing, pain, or recurrent infection. Allergies, infection, inflammation, and structural factors contribute; persistent hearing loss or severe pain needs examination.",
  "Exocrine Pancreatic Insufficiency EPI" => "Exocrine pancreatic insufficiency occurs when the pancreas does not release enough digestive enzymes, causing greasy stools, bloating, weight loss, and deficiencies of fat-soluble vitamins. Pancreatic enzyme replacement and nutritional monitoring are central to treatment.",
  "Eye Allergy" => "An eye allergy is an immune reaction to airborne or contact allergens that causes itching, redness, tearing, and swollen eyelids. Avoidance, cool compresses, lubricants, and appropriate antiallergic drops help; pain or vision loss suggests a different urgent condition.",
  "Eye Care" => "Eye care includes protective eyewear, regular examination based on age and risk, control of diabetes and blood pressure, safe contact-lens hygiene, and prompt attention to vision changes. Sudden vision loss, severe pain, flashes, or a curtain-like shadow is urgent.",
  "Eye Floaters" => "Eye floaters are spots, threads, or cobweb-like shapes caused by shadows from material in the vitreous. Long-standing stable floaters are often benign, but a sudden increase with flashes or a visual curtain may indicate retinal tear or detachment.",
  "Eye Strain" => "Eye strain causes tired, dry, burning, blurred, or achy eyes after prolonged visual tasks. Breaks, blinking, appropriate lighting, screen distance, lubrication, and correction of refractive error can help; persistent symptoms need an eye examination.",
  "Eyeglasses, Sunglasses, and Magnifiers" => "Eyeglasses correct refractive errors, sunglasses reduce glare and ultraviolet exposure, and magnifiers enlarge near targets for selected visual impairment. Prescription, fit, lens protection, and the underlying eye condition determine the appropriate aid.",
  "Fabry's Disease" => "Fabry disease is an X-linked lysosomal storage disorder caused by deficient alpha-galactosidase A and accumulation of globotriaosylceramide. It can cause burning limb pain, angiokeratomas, kidney disease, heart disease, stroke, and heat or sweat abnormalities.",
  "Facial Nerve Problems" => "Facial-nerve disorders can cause weakness or paralysis of facial expression, altered taste, sound sensitivity, tearing changes, or inability to close an eye. Causes include Bell palsy, infection, tumor, trauma, stroke, and autoimmune disease; sudden weakness requires urgent assessment.",
  "Factitious Disorders" => "Factitious disorder involves deliberately producing or falsifying illness behavior to assume the sick role, without an obvious external reward. It is a mental-health disorder requiring nonjudgmental assessment, protection from unnecessary procedures, and coordinated psychiatric and medical care.",
  "Fainting" => "Fainting is brief loss of consciousness from transient reduced brain perfusion, often due to reflex mechanisms, standing, dehydration, or cardiac disease. Evaluation is urgent when it occurs during exertion, with chest pain, palpitations, injury, abnormal heart findings, or family history of sudden death.",
  "Farsightedness" => "Farsightedness, or hyperopia, occurs when light focuses behind the retina, causing near blur, eyestrain, or headaches. Children may compensate and develop amblyopia; glasses, contact lenses, or selected procedures correct the focusing error.",
  "Fatigue" => "Fatigue is reduced energy or stamina that may result from sleep problems, anemia, infection, endocrine disease, medicines, depression, chronic inflammation, cancer, or overexertion. Persistent or function-limiting fatigue requires assessment rather than treatment with stimulants alone.",
  "Fatty Liver" => "Fatty liver is excess fat accumulation in liver cells, commonly related to metabolic disease, alcohol, medicines, or nutrition. It may be silent but can progress to inflammation, fibrosis, cirrhosis, and cancer; weight, alcohol, glucose, lipid, and liver-risk management help.",
  "Febrile Seizures" => "Febrile seizures are convulsions triggered by fever in young children without evidence of an intracranial infection or prior unprovoked seizure. Most are brief and self-limited, but a first seizure, prolonged event, breathing problem, or incomplete recovery needs emergency care.",
  "Fecal Incontinence" => "Fecal incontinence is involuntary leakage of stool or mucus due to weakness or injury of the anal sphincters, altered sensation, diarrhea, constipation, nerve disease, or pelvic-floor dysfunction. Treatment may include bowel regulation, pelvic-floor therapy, medicines, or surgery.",
  "Felty's Syndrome" => "Felty syndrome is a rare complication of long-standing seropositive rheumatoid arthritis characterized by neutropenia and often an enlarged spleen. It increases infection risk and may require disease-modifying therapy, growth factors, antibiotics, or specialist treatment.",
  "Female Reproductive System" => "The female reproductive system includes the ovaries, fallopian tubes, uterus, cervix, vagina, vulva, and related hormonal pathways. It supports ovulation, menstruation, pregnancy, birth, and sexual function and is affected by developmental, endocrine, infectious, and structural disorders.",
  "Fever and Headache" => "Fever with headache may occur with viral illness, influenza, sinus disease, dehydration, meningitis, encephalitis, or other infection. Severe sudden headache, neck stiffness, confusion, rash, seizure, weakness, or reduced consciousness requires emergency assessment.",
  "Fibrocystic Breast Condition" => "Fibrocystic breast change causes lumpiness, tenderness, or cysts that often vary with the menstrual cycle. It is usually benign, but a new persistent or changing mass, skin or nipple change, or bloody discharge needs clinical and imaging assessment.",
  "Fibromyalgia Facts" => "Fibromyalgia is a chronic pain-amplification disorder with widespread pain, fatigue, unrefreshing sleep, cognitive symptoms, and sensitivity to stimuli. Diagnosis is clinical after considering other causes; exercise, sleep treatment, education, psychological therapy, and selected medicines can help.",
  "Fifth Disease" => "Fifth disease is a common childhood infection caused by parvovirus B19, often producing mild fever followed by a slapped-cheek rash and lacy body rash. It can be serious in pregnancy, hemolytic anemia, or immune deficiency.",
  "Finger Dislocation" => "A finger dislocation occurs when a joint surface is forced out of alignment, causing pain, swelling, deformity, and limited motion. Prompt reduction and assessment for fracture, tendon injury, nerve damage, and vascular compromise help prevent stiffness and instability.",
  "First Aid" => "First aid is immediate care that preserves life, prevents deterioration, and supports recovery until professional help arrives. Priorities include scene safety, emergency activation, airway and breathing, severe bleeding control, recovery positioning, and condition-specific measures.",
  "Flakka" => "Flakka is a street name for potent synthetic cathinone stimulants, often alpha-PVP, that can cause agitation, paranoia, delirium, seizures, dangerously high temperature, muscle breakdown, arrhythmia, or cardiovascular collapse. Severe toxicity requires emergency care.",
  "Flea Bites in Humans" => "Flea bites cause small itchy papules, often clustered around the ankles or lower legs, and may trigger allergic reactions. Fleas can transmit infections in some settings; control requires treating pets and the environment as well as symptoms.",
  "Folliculitis" => "Folliculitis is inflammation or infection of hair follicles, producing itchy or tender red bumps, pustules, or crusts. Bacteria, yeast, friction, shaving, occlusion, and medicines can contribute; treatment ranges from hygiene and topical care to targeted antimicrobial therapy.",
  "Food Allergy" => "Food allergy is an immune reaction to a food protein that can cause hives, swelling, vomiting, wheezing, or anaphylaxis soon after exposure. Avoidance, label awareness, an emergency action plan, and prescribed epinephrine are important.",
  "Food Poisoning" => "Food poisoning is illness from contaminated food or drink, caused by bacteria, viruses, parasites, toxins, or chemicals. Diarrhea, vomiting, cramps, and fever are common; dehydration, bloody stool, neurologic symptoms, or illness in a high-risk person requires care.",
  "Foot Pain" => "Foot pain may arise from injury, overuse, plantar fascia disease, arthritis, nerve compression, infection, poor footwear, or vascular disease. Inability to bear weight, deformity, fever, numbness, discoloration, or diabetes increases the need for prompt assessment.",
  "Freckles" => "Freckles are small flat areas of increased melanin that darken with ultraviolet exposure and often reflect genetic tendency. They are usually harmless, but a changing, bleeding, irregular, or distinctly different pigmented lesion should be examined.",
  "Frequent Urination" => "Frequent urination can result from excess fluid or caffeine, urinary infection, diabetes, pregnancy, diuretics, prostate disease, overactive bladder, or kidney disorders. Burning, fever, blood, excessive thirst, weight loss, or nighttime symptoms guide evaluation.",
  "Friedreichs Ataxia Syndrome" => "Friedreich ataxia is an inherited neurodegenerative disorder, usually autosomal recessive, caused by reduced frataxin and mitochondrial dysfunction. It causes progressive gait and limb ataxia, neuropathy, scoliosis, cardiomyopathy, and sometimes diabetes.",
  "Frostbite" => "Frostbite is tissue injury from freezing, causing numbness, pale or waxy skin, swelling, blisters, and possible tissue death. Rewarming must be controlled and medical assessment is needed for deep injury, extensive exposure, or systemic hypothermia.",
  "Frozen Shoulder" => "Frozen shoulder, or adhesive capsulitis, causes progressive pain and marked restriction of both active and passive shoulder motion. It may follow injury, diabetes, or prolonged immobility and often improves with staged physical therapy, injections, and time.",
  "Fungal Arthritis" => "Fungal arthritis is infection of a joint by a fungus, usually after surgery, injection, trauma, bloodstream spread, or immune suppression. It causes pain, swelling, and restricted movement and requires joint sampling, prolonged antifungal therapy, and sometimes surgery.",
  "Fungal Nails" => "Fungal nail infection causes thickened, discolored, brittle, separated, or distorted nails. Diagnosis may require microscopy or culture because trauma and inflammatory nail disease look similar; treatment may be topical or oral and requires attention to liver and medicine risks.",
  "Gallstones" => "Gallstones are hardened deposits in the gallbladder that may be silent or cause biliary pain, cholecystitis, pancreatitis, or bile-duct obstruction. Persistent right-upper-abdominal pain, fever, jaundice, or vomiting requires prompt evaluation.",
  "Gambling Addiction" => "Gambling disorder is persistent impaired control over gambling despite financial, relationship, occupational, or emotional harm. Treatment may include cognitive behavioral therapy, financial safeguards, peer support, and care for depression, substance use, or suicidality.",
  "Ganglion" => "A ganglion is a benign fluid-filled cyst arising near a joint or tendon sheath, commonly at the wrist. It may fluctuate in size and cause pain, pressure, or numbness; observation, aspiration, or surgery is considered according to symptoms.",
  "Gangrene" => "Gangrene is tissue death caused by loss of blood supply, infection, or both. It can be dry, wet, or gas-forming and may occur in limbs, skin, bowel, or other organs; urgent treatment addresses circulation, infection, debridement, and systemic shock.",
  "Gardner Syndrome" => "Gardner syndrome is a familial adenomatous polyposis variant caused by APC-gene mutations, with numerous colorectal polyps and possible osteomas, dental abnormalities, desmoid tumors, and other lesions. Regular surveillance and preventive colorectal management are essential.",
  "Gastritis" => "Gastritis is inflammation or injury of the stomach lining caused by Helicobacter pylori, nonsteroidal anti-inflammatory drugs, alcohol, autoimmune disease, stress-related illness, or other factors. It may cause pain, nausea, bleeding, or no symptoms.",
  "Gastroesophageal Junction Adenocarcinoma" => "Gastroesophageal-junction adenocarcinoma is a gland-forming cancer arising where the esophagus meets the stomach. Difficulty swallowing, reflux, bleeding, or weight loss may occur; endoscopy, biopsy, staging, and tumor testing guide treatment.",
  "Gastrointestinal Stromal Tumor Soft Tissue Sarcoma" => "A gastrointestinal stromal tumor is a mesenchymal cancer of the digestive tract, often driven by KIT or PDGFRA signaling. It may cause bleeding, pain, obstruction, or an incidental mass and is treated according to size, site, mutation, and spread.",
  "Gastroparesis" => "Gastroparesis is delayed stomach emptying without a mechanical blockage, causing early fullness, nausea, vomiting, bloating, and unstable glucose. Diabetes, surgery, medicines, and neurologic disease can contribute; diet changes, medicines, nutrition support, and targeted procedures may help.",
  "Gaucher Disease" => "Gaucher disease is an inherited lysosomal storage disorder caused by deficient glucocerebrosidase, leading to enlarged spleen or liver, anemia, low platelets, bone disease, and sometimes neurologic involvement. Enzyme or substrate-reduction therapy may be effective.",
  "Genetic Disease" => "A genetic disease results from a pathogenic change in DNA or chromosome structure and may be inherited or arise anew. Effects depend on the gene, variant, inheritance pattern, and environment; diagnosis can involve family history, examination, and genetic testing.",
  "Genital Herpes in Women Overview" => "Genital herpes is infection with herpes simplex virus causing painful blisters or ulcers, though many infections are unrecognized. Antiviral treatment reduces symptoms and transmission, and pregnancy requires obstetric planning because neonatal infection can be severe.",
  "Genital Warts In Women" => "Genital warts are growths caused by low-risk human papillomavirus types and may occur on vulvar, vaginal, cervical, or perianal skin. Treatments remove visible lesions but may not eradicate the virus; vaccination and cervical screening remain important.",
  "GERD in Infants and Children" => "Gastroesophageal reflux is common in infants, but GERD causes troublesome symptoms or complications such as poor growth, feeding refusal, pain, or respiratory problems. Feeding measures, assessment for other causes, and selective treatment depend on age and severity.",
  "Gestational Diabetes" => "Gestational diabetes is glucose intolerance first recognized during pregnancy. It increases risks of excessive fetal growth, birth complications, hypertensive disease, and later type 2 diabetes; management uses nutrition, activity, glucose monitoring, medicines when needed, and postpartum testing.",
  "Giardia Lamblia" => "Giardia lamblia is a parasite acquired through contaminated water, food, hands, or close contact and causes diarrhea, bloating, cramps, nausea, and malabsorption. Testing and antiparasitic treatment are used, with attention to hydration and reinfection prevention.",
  "Gilbert Syndrome" => "Gilbert syndrome is a common benign inherited reduction in bilirubin conjugation that causes intermittent mild unconjugated jaundice, often during fasting, illness, stress, or dehydration. It usually does not damage the liver or require treatment.",
  "Glaucoma" => "Glaucoma is optic-nerve damage often associated with elevated or fluctuating eye pressure, leading to progressive visual-field loss. It may be silent until advanced; pressure-lowering drops, laser, or surgery preserve vision but do not restore lost nerve tissue.",
  "Gluteal Injury" => "A gluteal injury may involve muscle strain, tendon damage, contusion, hematoma, nerve irritation, or fracture around the hip or pelvis. Pain, bruising, weakness, inability to walk, numbness, or severe trauma guides the need for imaging and treatment.",
  "Glycemic Index High vs Low-Glycemic Foods" => "The glycemic index ranks how quickly a carbohydrate-containing food raises blood glucose compared with a reference. Portion size, fiber, processing, mixed meals, and individual response also matter, so the index is one planning tool rather than a complete diet rule.",
  "Gonorrhea In Women" => "Gonorrhea is a sexually transmitted infection caused by Neisseria gonorrhoeae and may cause discharge, pelvic pain, painful urination, or no symptoms in women. Untreated infection can cause pelvic inflammatory disease, infertility, ectopic pregnancy, or disseminated disease.",
  "Granulomatosis With Polyangiitis" => "Granulomatosis with polyangiitis is an autoimmune small- and medium-vessel vasculitis that commonly affects the sinuses, lungs, and kidneys. It can cause destructive respiratory disease, bleeding, kidney failure, or systemic inflammation and requires specialist immunosuppression.",
  "Group B Strep" => "Group B Streptococcus can colonize the gastrointestinal or genital tract without symptoms but can cause urinary, wound, bloodstream, or newborn infection. Pregnancy screening and intrapartum antibiotics reduce the risk of early-onset neonatal disease.",
  "Gum Disease" => "Gum disease begins as gingivitis from plaque and may progress to periodontitis with loss of tooth-supporting bone. Bleeding, swelling, recession, bad breath, and loose teeth are warning signs; professional cleaning, oral hygiene, and treatment of risk factors help.",
  "Gum Problems" => "Gum problems include inflammation, bleeding, recession, ulcers, infection, trauma, and growths. Causes include plaque, tobacco, dry mouth, medicines, nutritional or immune disease, and poorly fitting appliances; persistent lesions or bleeding need dental assessment.",
  "Hamstring Injury" => "A hamstring injury is overstretching or tearing of the muscles at the back of the thigh, usually during sprinting or sudden acceleration. Pain, bruising, weakness, and difficulty walking may occur; graded rehabilitation reduces reinjury.",
  "Hand-Foot-And-Mouth Syndrome" => "Hand-foot-and-mouth disease is a viral illness, commonly from enteroviruses, causing fever, mouth sores, and a rash or blisters on hands and feet. It usually resolves with supportive care but can spread readily among children.",
  "Head Lice" => "Head lice are parasitic insects that live on the scalp and feed on blood, causing itching and visible nits or lice. They spread mainly through close head contact; treatment requires an effective pediculicide or combing plan and household contact management.",
  "Heart Attack Prevention" => "Heart-attack prevention targets blood pressure, atherogenic cholesterol, diabetes, tobacco exposure, diet, physical activity, weight, sleep, and adherence to prescribed medicines. Risk-based preventive treatment is more effective than relying on one supplement or symptom.",
  "Heart: How the Heart Works" => "The heart is a muscular pump with four chambers and valves that direct blood through the lungs and body. Electrical conduction coordinates contraction, while coronary arteries supply the heart muscle; disease can affect rhythm, muscle, valves, vessels, or filling.",
  "Hodgkin's and Non-Hodgkin's Lymphoma Comparison" => "Hodgkin lymphoma is defined by characteristic Reed-Sternberg cells and commonly spreads in an orderly pattern, while non-Hodgkin lymphomas comprise many B-cell, T-cell, and other lymphoid cancers. Biopsy, immunophenotyping, and staging determine treatment and prognosis.",
  "Heat Exhaustion" => "Heat exhaustion results from excessive heat exposure and fluid or salt loss, causing heavy sweating, weakness, headache, nausea, dizziness, and cool clammy skin. Move to a cool place, rehydrate when alert, and seek emergency help if confusion, collapse, or hot dry skin develops.",
  "Heat Stroke" => "Heat stroke is life-threatening failure of heat regulation with very high body temperature and brain dysfunction such as confusion, seizure, or unconsciousness. Call emergency services and begin rapid cooling immediately; do not delay for oral fluids or medications.",
  "Helicobacter Pylori" => "Helicobacter pylori is a stomach bacterium associated with gastritis, peptic ulcers, and increased risk of gastric cancer and some lymphomas. Breath, stool, or biopsy testing can diagnose it, and eradication requires combination treatment.",
  "Hemolytic Uremic Syndrome" => "Hemolytic uremic syndrome causes destruction of red blood cells, low platelets, and acute kidney injury, often after Shiga-toxin-producing diarrheal infection. Reduced urine, pallor, bruising, bloody diarrhea, or weakness requires urgent pediatric or medical evaluation.",
  "Henoch-Schonlein Purpura" => "Henoch-Schönlein purpura, now IgA vasculitis, inflames small vessels and causes palpable purpura, joint pain, abdominal symptoms, and kidney involvement, mainly in children. Follow-up urine and blood-pressure monitoring is needed because kidney disease may appear later.",
  "Hepatitis B" => "Hepatitis B is a viral infection that can be acute or chronic and may cause liver inflammation, cirrhosis, liver failure, or cancer. Vaccination prevents it; testing, antiviral treatment when indicated, and evaluation of household or sexual contacts reduce harm.",
  "Hepatitis C" => "Hepatitis C is a blood-borne viral infection that often remains silent while causing chronic liver inflammation, cirrhosis, cancer, and extrahepatic disease. Modern direct-acting antivirals can cure most infections after appropriate testing and staging.",
  "Hiatal Hernia Overview" => "A hiatal hernia occurs when part of the stomach moves through the diaphragm into the chest. It may cause reflux, chest or upper-abdominal discomfort, swallowing problems, or no symptoms; treatment ranges from lifestyle and acid control to surgery.",
  "High Blood Pressure Hypertension" => "Hypertension is persistently elevated arterial pressure that increases the risk of stroke, heart disease, kidney disease, eye damage, and dementia. Diagnosis uses repeated accurate measurements, and management combines lifestyle measures with medicines when indicated.",
  "High White Blood Cell Count in Pregnancy" => "A mild rise in white blood cells can be normal during pregnancy, labor, or stress. Marked or persistent elevation with fever, pain, urinary or respiratory symptoms, or abnormal differential counts may indicate infection, inflammation, medication effect, or another disorder.",
  "Hip Bursitis" => "Hip bursitis is inflammation of a bursa near the hip, commonly causing pain over the outer hip that worsens with lying on that side, stairs, or prolonged walking. Activity changes, physical therapy, medicines, or injection may help after other causes are considered.",
  "Hirschsprung Disease" => "Hirschsprung disease is congenital absence of nerve cells in part of the colon, preventing normal relaxation and stool movement. Newborn obstruction, delayed meconium, abdominal distension, or severe constipation may occur; surgical removal of the affected segment is definitive treatment.",
  "Hives" => "Hives, or urticaria, are transient raised itchy welts caused by histamine release in the skin. Triggers include infection, foods, medicines, temperature, pressure, or autoimmune disease; lip or tongue swelling, breathing difficulty, or faintness signals anaphylaxis.",
  "Hoarseness" => "Hoarseness is altered voice quality from inflammation, overuse, vocal-cord lesions, reflux, nerve disease, smoking, or cancer. Persistent hoarseness, pain, swallowing difficulty, coughing blood, breathing trouble, or a neck mass requires examination of the larynx.",
  "Hydronephrosis" => "Hydronephrosis is dilation of the kidney collecting system caused by impaired urine drainage from obstruction, reflux, stones, strictures, tumors, or pregnancy. It can damage kidney function and requires treatment of the cause, especially with fever, pain, or reduced urine.",
  "Hydroxyapatite" => "Hydroxyapatite is a calcium-phosphate mineral that forms much of bone and tooth enamel and is also found in some calcific deposits around joints. Abnormal deposits can cause painful tendinitis or bursitis and are evaluated according to location and symptoms.",
  "Hyperhidrosis" => "Hyperhidrosis is excessive sweating beyond what is needed for temperature regulation, either generalized or focused on areas such as palms, feet, or underarms. It may be primary or caused by medicines, endocrine disease, infection, or neurologic illness.",
  "Hyperkalemia" => "Hyperkalemia is an abnormally high blood potassium level that can disrupt cardiac conduction and cause weakness or dangerous arrhythmias. Kidney disease, medicines, tissue breakdown, and laboratory artifact are common contributors; severe or symptomatic cases require urgent treatment.",
  "Hypersensitivity Pneumonitis" => "Hypersensitivity pneumonitis is immune-mediated inflammation of lung tissue after repeated inhalation of an antigen such as mold, birds, or agricultural dust. Exposure avoidance is central; ongoing disease can cause fibrosis, breathlessness, cough, and impaired lung function.",
  "Hyperthermia" => "Hyperthermia is an abnormally high body temperature from excess heat production or failed heat loss rather than a regulated fever. Causes include environmental heat, exertion, medicines, toxins, anesthesia, or endocrine crisis; neurologic change makes it an emergency.",
  "Hypothyroidism" => "Hypothyroidism is insufficient thyroid hormone activity, causing fatigue, cold intolerance, constipation, dry skin, slowed heart rate, weight change, and cognitive or mood symptoms. Thyroid testing confirms it, and levothyroxine replacement is standard for many patients.",
  "Hypoxia and Hypoxemia" => "Hypoxemia is low oxygen in arterial blood, while hypoxia is inadequate oxygen at the tissue level. Causes include lung disease, airway obstruction, heart disease, anemia, shock, or high altitude; severe breathlessness, cyanosis, confusion, or collapse is urgent.",
  "IBS-D Irrititable Bowel Syndrome with Diarrhea" => "IBS with diarrhea causes recurrent abdominal pain associated with loose stools without structural disease explaining the symptoms. Management may include diet changes, soluble fiber, gut-directed medicines, behavioral therapy, and evaluation for alarm features or alternative diagnoses.",
  "Ichthyosis Vulgaris" => "Ichthyosis vulgaris is a common inherited or acquired scaling disorder caused by impaired skin-barrier shedding, producing dry fish-like scale often worse on the legs. Regular emollients, keratolytics, gentle bathing, and treatment of an underlying disorder can improve it.",
  "ICU Psychosis" => "ICU psychosis is an informal term for delirium in critically ill patients, with fluctuating attention, confusion, altered perception, and sleep-wake disruption. Infection, medications, organ failure, pain, and hypoxia contribute; treatment addresses causes and supports orientation and safety.",
  "Iliotibial Band Syndrome" => "Iliotibial-band syndrome is overuse pain on the outer knee or hip caused by irritation of the iliotibial band during repetitive flexion and extension. Training modification, hip and leg strengthening, flexibility work, and gradual return to activity are typical treatments.",
  "Impetigo" => "Impetigo is a superficial bacterial skin infection causing fragile blisters or honey-colored crusts, often around the nose and mouth. It spreads by contact and is treated with hygiene and topical or oral antibiotics according to extent and organism.",
  "Impingement Syndrome" => "Shoulder impingement describes painful compression or irritation of tendons and bursa during arm elevation, often related to rotator-cuff disease or altered mechanics. Activity modification, rehabilitation, analgesia, and selected injections or surgery may help.",
  "Infant Formulas" => "Infant formulas provide nutritionally designed substitutes or supplements to human milk when needed. Choice depends on age, tolerance, allergy, prematurity, metabolic disease, and feeding goals; safe preparation and discard practices prevent contamination and excess concentration.",
  "Infectious Mononucleosis" => "Infectious mononucleosis is usually caused by Epstein-Barr virus and produces fatigue, fever, sore throat, swollen lymph nodes, and sometimes an enlarged spleen. Rest and symptom care are typical; contact sports should be avoided until splenic risk is assessed.",
  "Inflammatory Bowel Disease: Intestinal Problems" => "Inflammatory bowel disease, including Crohn disease and ulcerative colitis, causes chronic immune-mediated intestinal inflammation with diarrhea, pain, bleeding, weight loss, and extraintestinal effects. Treatment aims for sustained remission and prevention of structural and nutritional complications.",
  "Inflammatory Breast Cancer" => "Inflammatory breast cancer is an aggressive breast cancer that blocks lymphatic drainage, causing rapid redness, swelling, warmth, skin thickening, and sometimes no discrete lump. Diagnosis requires imaging and biopsy; multimodal systemic and local treatment is used.",
  "Influenza" => "Influenza is an acute respiratory infection caused by influenza viruses, often producing abrupt fever, aches, headache, cough, sore throat, and fatigue. Vaccination helps prevent it, and early antiviral treatment is important for high-risk or severely ill patients.",
  "Ingrown Hair" => "An ingrown hair curves back into the skin or fails to exit the follicle, causing an itchy or tender bump, inflammation, or infection. Avoiding close hair removal, reducing friction, and gentle skin care help; recurrent scarring may need dermatologic treatment.",
  "Ingrown Toenail" => "An ingrown toenail occurs when the nail edge penetrates adjacent skin, causing pain, redness, swelling, and sometimes infection. Proper trimming and footwear help early cases; drainage, pus, severe pain, diabetes, or recurrence may require clinical treatment.",
  "Inner Ear Infection" => "Inner-ear inflammation can affect hearing and balance, producing vertigo, nausea, tinnitus, or hearing loss. Causes include viral infection, bacterial disease, autoimmune inflammation, or other disorders; sudden hearing loss, severe imbalance, or neurologic signs requires urgent assessment.",
  "Insect Sting Allergies" => "Insect-sting allergy can cause reactions ranging from local swelling to generalized hives, airway swelling, low blood pressure, and anaphylaxis. People with systemic reactions may need an epinephrine plan, allergist evaluation, venom immunotherapy, and prevention measures.",
  "Insomnia" => "Insomnia is difficulty falling asleep, staying asleep, or obtaining restorative sleep despite adequate opportunity, with daytime impairment. Causes include stress, mood disorders, pain, medicines, substances, circadian disruption, and sleep apnea; cognitive behavioral therapy for insomnia is first-line treatment.",
  "Insulin Resistance" => "Insulin resistance occurs when muscle, liver, and fat cells respond inadequately to insulin, leading the pancreas to produce more. It is associated with prediabetes, type 2 diabetes, fatty liver, polycystic ovary syndrome, and cardiovascular risk and may improve with activity and weight care.",
  "Internal Bleeding" => "Internal bleeding is blood loss into a body cavity, tissue, or organ rather than through an obvious external wound. Trauma, ulcers, aneurysm, pregnancy complications, medicines, and tumors can cause it; faintness, shock, abdominal swelling, black stool, or vomiting blood is an emergency.",
  "Interstitial Cystitis" => "Interstitial cystitis, or bladder pain syndrome, causes bladder or pelvic pain, urinary urgency, frequency, and discomfort without a proven infection explaining symptoms. Treatment is individualized and may include bladder training, pelvic therapy, medicines, instillation, or procedures.",
  "Intertrigo" => "Intertrigo is inflammation in skin folds caused by moisture, friction, heat, and impaired ventilation, sometimes complicated by Candida or bacteria. It produces redness, soreness, maceration, odor, or erosions; drying, barrier care, and targeted treatment help.",
  "Intussusception" => "Intussusception occurs when one segment of intestine telescopes into another, causing obstruction and reduced blood flow, especially in infants and young children. Intermittent severe pain, vomiting, lethargy, or bloody stool requires emergency imaging and reduction.",
  "Iritis" => "Iritis is inflammation of the iris, often part of anterior uveitis, causing eye pain, redness around the cornea, light sensitivity, blurred vision, and a small or irregular pupil. Prompt ophthalmic treatment prevents synechiae, glaucoma, and vision loss.",
  "Iron Overload" => "Iron overload is excessive iron accumulation from inherited hemochromatosis, transfusions, supplements, or other disease. It can injure the liver, heart, pancreas, joints, and endocrine organs; testing, phlebotomy or chelation, and treatment of the cause are used.",
  "Itch" => "Itch, or pruritus, is an unpleasant skin sensation that provokes scratching and may arise from dermatitis, allergy, infection, medicines, kidney or liver disease, blood disorders, nerve disease, or systemic illness. Persistent generalized itch requires evaluation.",
  "Jaundice in Adults" => "Adult jaundice is yellowing of skin or eyes from elevated bilirubin due to red-cell breakdown, liver injury, impaired bile flow, or inherited metabolism. Dark urine, pale stool, abdominal pain, fever, confusion, or rapid onset requires prompt assessment.",
  "Jet Lag" => "Jet lag is temporary circadian misalignment after rapid travel across time zones, causing sleep disturbance, daytime fatigue, poor concentration, and gastrointestinal symptoms. Light timing, gradual schedule adjustment, sleep planning, and selected melatonin use may help.",
  "Jock Itch" => "Jock itch is a superficial dermatophyte infection of the groin and inner thighs, producing an itchy scaly border and relative sparing of the scrotum. Keeping skin dry and using an appropriate antifungal treatment helps; persistent or atypical rash needs diagnosis.",
  "Juvenile Arthritis" => "Juvenile idiopathic arthritis is chronic inflammatory arthritis beginning before age 16 and lasting at least six weeks after other causes are excluded. It can affect joints, eyes, growth, and organs; treatment aims to control inflammation and preserve function."
}.freeze

def excluded_title?(term)
  term =~ /^(Can |Do |Does |Are |Is |What |Why |How |Best |Fastest |First Signs|Early |Easiest |Eat |Eating |Exercises |Foods |Figure |Father|Dealing|Difference|Differences|Disadvantages|Dandruff vs|Drink |Drinking |Duration|Good |Get |Get Rid|Having |Healthy Living|Health and|Tips|Ways|Should I|Should You|Before|After|A-Z|Common|Cochlear|Four |Exposure Media|Directives|Advantages|Coping|Dream|Weigh|Weight|e-Cigarettes|Ear Care|Electrolysis|Embryo vs|Emotional Eating|Erectile Dysfunction Caused|Frankincense|Gastroparesis Diet|Genital Herpes and Cold Sores|GERD:|Have to Be Over|Health Benefits|Heart Attack vs|Heart:|Home Remedies|Homemade Remedy|Hormone Replacement Therapy|Hospital Stay|Hydrogen Peroxide|IBS vs|If Patellofemoral|Importance:|Indoor Allergens|Innie vs|Dandruff)/i
end

def latex_escape(value)
  value.gsub('&', '\\&').gsub('%', '\\%').gsub('#', '\\#')
end

%w[E F G H I J].each do |letter|
  input = "/tmp/medicinenet_#{letter}_terms.txt"
  output = "chapters/med_terms_#{letter.downcase}.tex"
  text = File.read(output)
  existing = text.scan(/^\\medterm\{([^}]*)\}/).flatten.to_h { |title| [normalize(title), true] }
  terms = File.readlines(input, chomp: true).reject do |term|
    excluded_title?(term) || term =~ /^(Health A-Z|Drugs & Medications|Diseases & Conditions|Medical Slideshows|Procedures & Tests|Medications|Image Collection|Quizzes|More\.\.\.)$/
  end
  additions = []

  terms.each do |term|
    next if existing[normalize(term)]
    definition = DEFINITIONS[term]
    unless definition
      opening = term.index('(')
      definition = "Alternate index label for #{latex_escape(term[(opening + 1)...-1])}." if opening
    end
    raise "No specific definition for #{term}" unless definition
    additions << [term, definition]
  end

  File.open(output, 'a') do |file|
    additions.each do |term, definition|
      file.puts
      file.puts "\\medterm{#{term}} #{definition}"
      file.puts
      file.puts '\\synonyms'
    end
  end
  puts "#{letter}: added #{additions.length} terms"
end
